In [1]:
import json
import pandas as pd
import statistics
from functools import reduce

In [2]:
def prepare_dataframe(res_dict, msg, m_lst = ['F1-Weighted'], sota=''):
    for d, exp_dict in res_dict.items():
        out_dict = {}
        # print(d, len(exp_dict['Org']), 'Org')
        if 'Org' in exp_dict:
            for splt_item in exp_dict['Org']:
                for m in m_lst:
                    v = splt_item[2]['Org'][0][m]
                    # print(v, splt_item)
                    k = msg + '.' + m[:4] + '.' + 'Org'
                    if not k in out_dict:
                        out_dict[k] = []    
                    out_dict[k].append(v)
        for CF, splt_items in exp_dict['CF'].items():
            for splt_item in splt_items:
                # print(CF, splt_item)
                for m in m_lst:
                    v = splt_item[2]['CF'][0][m]
                    k = msg + '.' + m[:4] + '.' + sota + 'CF-' + CF[:3]
                    if not k in out_dict:
                        out_dict[k] = []
                    out_dict[k].append(v)
        _res_df = pd.DataFrame(out_dict)
        _res_df.loc['Mean'] = _res_df.mean()
        _dict = _res_df.loc['Mean'].to_dict()
        out_dict = {}
        out_dict['Domain'] = d
        if 'Org' in exp_dict:
            k = msg + '.' + m[:4] + '.' + 'Org'
            nk = '$' + msg + '.' + m[:2] + '_' + m[3] + '$'
            out_dict[nk] = f'{round(_dict[k], 3):.3f}'
            del _dict[k]
        for i, (_k, v) in enumerate(sorted(_dict.items(), key=lambda x:x[1], reverse=True)[:1]):
            k = msg + '.' + m[:4] + '.' + 'CF'
            nk = '$' + msg + '.' + m[:2] + '_' + m[3] + '.' + sota + 'cf' + '$'
            # if i == 1:
            #     nk += ' 2nd'
            # nk += ' Best'
            out_dict[nk] = f'{round(v, 3):.3f}' + '$_{cf=' + _k[-3:]+'}$'
        yield d, _res_df, out_dict

In [3]:
tpot_res_pj_file = 'out/tpot-lshs22-pj.json'
dav_res_pj_file = 'out/davidson-pipline-lshs22-pj.json'

tpot_pj_dict = json.load(open(tpot_res_pj_file, "r"))
dav_pj_dict = json.load(open(dav_res_pj_file, "r"))

In [4]:
res_m_pj_lst = []
for domain, _df, _res_dict in  prepare_dataframe(tpot_pj_dict, 'TPOT', m_lst = ['F1-Macro'], sota='pj.'):
    res_m_pj_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,TPOT.F1-M.pj.CF-0.1,TPOT.F1-M.pj.CF-0.2,TPOT.F1-M.pj.CF-0.3,TPOT.F1-M.pj.CF-0.4,TPOT.F1-M.pj.CF-0.5,TPOT.F1-M.pj.CF-0.6,TPOT.F1-M.pj.CF-0.7,TPOT.F1-M.pj.CF-0.8,TPOT.F1-M.pj.CF-0.9,TPOT.F1-M.pj.CF-1.0
0,0.554662,0.539458,0.536369,0.543942,0.509443,0.535320,0.529327,0.524773,0.529348,0.523803
1,0.639820,0.648008,0.642842,0.630113,0.627162,0.621981,0.587868,0.561979,0.614546,0.618549
2,0.677293,0.669461,0.661692,0.649265,0.663172,0.655092,0.674738,0.633650,0.641441,0.641662
3,0.659193,0.656103,0.646005,0.649823,0.635787,0.635986,0.631795,0.622154,0.634378,0.634727
4,0.535099,0.531889,0.538319,0.535121,0.533543,0.534767,0.533763,0.514827,0.516217,0.529234
Mean,0.613213,0.608984,0.605045,0.601653,0.593821,0.596629,0.591498,0.571477,0.587186,0.589595

'Religion'

,TPOT.F1-M.pj.CF-0.1,TPOT.F1-M.pj.CF-0.2,TPOT.F1-M.pj.CF-0.3,TPOT.F1-M.pj.CF-0.4,TPOT.F1-M.pj.CF-0.5,TPOT.F1-M.pj.CF-0.6,TPOT.F1-M.pj.CF-0.7,TPOT.F1-M.pj.CF-0.8,TPOT.F1-M.pj.CF-0.9,TPOT.F1-M.pj.CF-1.0
0,0.541450,0.553691,0.553019,0.557106,0.564306,0.546094,0.537069,0.546367,0.542048,0.535984
1,0.662976,0.657457,0.625007,0.656906,0.680067,0.657715,0.615187,0.643945,0.631182,0.624890
2,0.662185,0.624483,0.658706,0.613372,0.654446,0.632253,0.650719,0.648410,0.621261,0.614697
3,0.624717,0.664618,0.669776,0.663122,0.675624,0.698045,0.624446,0.638063,0.635448,0.614894
4,0.469154,0.488422,0.490911,0.496527,0.491172,0.509767,0.488201,0.510002,0.483024,0.488524
Mean,0.592096,0.597734,0.599484,0.597407,0.613123,0.608775,0.583124,0.597357,0.582593,0.575798

'Race'

,TPOT.F1-M.pj.CF-0.1,TPOT.F1-M.pj.CF-0.2,TPOT.F1-M.pj.CF-0.3,TPOT.F1-M.pj.CF-0.4,TPOT.F1-M.pj.CF-0.5,TPOT.F1-M.pj.CF-0.6,TPOT.F1-M.pj.CF-0.7,TPOT.F1-M.pj.CF-0.8,TPOT.F1-M.pj.CF-0.9,TPOT.F1-M.pj.CF-1.0
0,0.529342,0.537385,0.534345,0.500820,0.538534,0.556864,0.540783,0.556465,0.529640,0.540239
1,0.558146,0.536356,0.508442,0.538269,0.527189,0.501491,0.521579,0.542522,0.526936,0.521660
2,0.632259,0.625151,0.648575,0.640102,0.586122,0.625334,0.642016,0.611917,0.614104,0.630269
3,0.677953,0.649703,0.702149,0.642050,0.674178,0.617291,0.622719,0.611779,0.657693,0.642772
4,0.544270,0.553034,0.555847,0.576473,0.559666,0.572916,0.566178,0.568856,0.563087,0.555399
Mean,0.588394,0.580326,0.589872,0.579543,0.577138,0.574779,0.578655,0.578308,0.578292,0.578068

'Politics'

,TPOT.F1-M.pj.CF-0.1,TPOT.F1-M.pj.CF-0.2,TPOT.F1-M.pj.CF-0.3,TPOT.F1-M.pj.CF-0.4,TPOT.F1-M.pj.CF-0.5,TPOT.F1-M.pj.CF-0.6,TPOT.F1-M.pj.CF-0.7,TPOT.F1-M.pj.CF-0.8,TPOT.F1-M.pj.CF-0.9,TPOT.F1-M.pj.CF-1.0
0,0.516054,0.485614,0.526415,0.470031,0.497364,0.519360,0.477154,0.473761,0.486891,0.444335
1,0.637217,0.667865,0.661673,0.678133,0.639718,0.633846,0.621510,0.635995,0.647089,0.636862
2,0.655948,0.645349,0.670279,0.647151,0.654713,0.638737,0.623427,0.651642,0.634640,0.602132
3,0.676606,0.677843,0.693704,0.713284,0.683702,0.692514,0.681816,0.654994,0.671078,0.625253
4,0.581143,0.637921,0.601356,0.580872,0.621976,0.600685,0.581932,0.605321,0.595720,0.590490
Mean,0.613393,0.622918,0.630685,0.617894,0.619494,0.617028,0.597168,0.604343,0.607084,0.579814

'Sports'

,TPOT.F1-M.pj.CF-0.1,TPOT.F1-M.pj.CF-0.2,TPOT.F1-M.pj.CF-0.3,TPOT.F1-M.pj.CF-0.4,TPOT.F1-M.pj.CF-0.5,TPOT.F1-M.pj.CF-0.6,TPOT.F1-M.pj.CF-0.7,TPOT.F1-M.pj.CF-0.8,TPOT.F1-M.pj.CF-0.9,TPOT.F1-M.pj.CF-1.0
0,0.535064,0.531719,0.545018,0.524291,0.525603,0.538443,0.514928,0.534188,0.510684,0.514690
1,0.659880,0.680511,0.640014,0.644849,0.645422,0.665241,0.637298,0.630159,0.626745,0.622801
2,0.701161,0.696495,0.667065,0.686960,0.649013,0.675611,0.665520,0.657117,0.679582,0.662416
3,0.702444,0.759671,0.743338,0.696721,0.663344,0.741356,0.667224,0.678021,0.694952,0.679847
4,0.687047,0.700268,0.688173,0.679595,0.678184,0.675740,0.644591,0.653889,0.665235,0.668249
Mean,0.657119,0.673733,0.656721,0.646483,0.632313,0.659278,0.625912,0.630675,0.635440,0.629601

In [5]:
res_w_pj_lst = []
for domain, _df, _res_dict in  prepare_dataframe(tpot_pj_dict, 'TPOT', m_lst = ['F1-Weighted'], sota='pj.'):
    res_w_pj_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,TPOT.F1-W.pj.CF-0.1,TPOT.F1-W.pj.CF-0.2,TPOT.F1-W.pj.CF-0.3,TPOT.F1-W.pj.CF-0.4,TPOT.F1-W.pj.CF-0.5,TPOT.F1-W.pj.CF-0.6,TPOT.F1-W.pj.CF-0.7,TPOT.F1-W.pj.CF-0.8,TPOT.F1-W.pj.CF-0.9,TPOT.F1-W.pj.CF-1.0
0,0.845051,0.835971,0.830375,0.838901,0.818947,0.828240,0.827404,0.819837,0.826466,0.819521
1,0.886510,0.882257,0.875630,0.866937,0.859636,0.855114,0.856754,0.847651,0.848594,0.853742
2,0.939496,0.930184,0.924328,0.914177,0.924158,0.918261,0.920003,0.913729,0.905122,0.905385
3,0.936090,0.933183,0.923244,0.925646,0.913240,0.912331,0.908461,0.899856,0.911075,0.911513
4,0.834954,0.830764,0.840340,0.836512,0.834201,0.836857,0.835429,0.813087,0.815516,0.830816
Mean,0.888420,0.882472,0.878783,0.876435,0.870036,0.870160,0.869610,0.858832,0.861355,0.864195

'Religion'

,TPOT.F1-W.pj.CF-0.1,TPOT.F1-W.pj.CF-0.2,TPOT.F1-W.pj.CF-0.3,TPOT.F1-W.pj.CF-0.4,TPOT.F1-W.pj.CF-0.5,TPOT.F1-W.pj.CF-0.6,TPOT.F1-W.pj.CF-0.7,TPOT.F1-W.pj.CF-0.8,TPOT.F1-W.pj.CF-0.9,TPOT.F1-W.pj.CF-1.0
0,0.834357,0.832788,0.830834,0.835052,0.828955,0.826721,0.827845,0.831879,0.823987,0.823705
1,0.896872,0.898033,0.892739,0.897234,0.894829,0.893143,0.886171,0.886268,0.883798,0.879236
2,0.920416,0.906891,0.915324,0.901446,0.908346,0.900543,0.904074,0.901393,0.899086,0.893740
3,0.913014,0.924536,0.925725,0.921112,0.919268,0.923844,0.905756,0.907962,0.903273,0.887237
4,0.783449,0.790362,0.796077,0.787991,0.797884,0.822998,0.811370,0.822965,0.807702,0.800593
Mean,0.869622,0.870522,0.872140,0.868567,0.869856,0.873450,0.867043,0.870093,0.863569,0.856902

'Race'

,TPOT.F1-W.pj.CF-0.1,TPOT.F1-W.pj.CF-0.2,TPOT.F1-W.pj.CF-0.3,TPOT.F1-W.pj.CF-0.4,TPOT.F1-W.pj.CF-0.5,TPOT.F1-W.pj.CF-0.6,TPOT.F1-W.pj.CF-0.7,TPOT.F1-W.pj.CF-0.8,TPOT.F1-W.pj.CF-0.9,TPOT.F1-W.pj.CF-1.0
0,0.885788,0.886389,0.884625,0.874943,0.885803,0.889526,0.884516,0.886348,0.883627,0.884130
1,0.904513,0.899771,0.891339,0.900352,0.895608,0.885216,0.894546,0.894982,0.895501,0.894639
2,0.913312,0.912764,0.914371,0.915133,0.886104,0.913539,0.912638,0.904771,0.903801,0.910568
3,0.930397,0.924033,0.925704,0.923853,0.929847,0.920600,0.919271,0.918735,0.920209,0.924418
4,0.769911,0.764573,0.776956,0.811294,0.806624,0.807589,0.799746,0.799587,0.809953,0.821387
Mean,0.880784,0.877506,0.878599,0.885115,0.880797,0.883294,0.882143,0.880885,0.882618,0.887028

'Politics'

,TPOT.F1-W.pj.CF-0.1,TPOT.F1-W.pj.CF-0.2,TPOT.F1-W.pj.CF-0.3,TPOT.F1-W.pj.CF-0.4,TPOT.F1-W.pj.CF-0.5,TPOT.F1-W.pj.CF-0.6,TPOT.F1-W.pj.CF-0.7,TPOT.F1-W.pj.CF-0.8,TPOT.F1-W.pj.CF-0.9,TPOT.F1-W.pj.CF-1.0
0,0.775005,0.775107,0.774879,0.771764,0.771994,0.766347,0.762286,0.766555,0.764154,0.752355
1,0.913587,0.915444,0.913478,0.909989,0.903614,0.903626,0.899367,0.902177,0.903917,0.896718
2,0.913482,0.912370,0.916196,0.899115,0.912507,0.905359,0.909088,0.907208,0.890249,0.889601
3,0.939606,0.937210,0.935248,0.943573,0.928233,0.932665,0.931678,0.923762,0.918583,0.915249
4,0.839039,0.859080,0.854269,0.849210,0.848993,0.852978,0.839906,0.855744,0.847346,0.839732
Mean,0.876144,0.879842,0.878814,0.874730,0.873068,0.872195,0.868465,0.871089,0.864850,0.858731

'Sports'

,TPOT.F1-W.pj.CF-0.1,TPOT.F1-W.pj.CF-0.2,TPOT.F1-W.pj.CF-0.3,TPOT.F1-W.pj.CF-0.4,TPOT.F1-W.pj.CF-0.5,TPOT.F1-W.pj.CF-0.6,TPOT.F1-W.pj.CF-0.7,TPOT.F1-W.pj.CF-0.8,TPOT.F1-W.pj.CF-0.9,TPOT.F1-W.pj.CF-1.0
0,0.874696,0.872587,0.872099,0.866859,0.867558,0.867254,0.859531,0.864119,0.856524,0.859363
1,0.953425,0.953339,0.947462,0.941127,0.952094,0.948066,0.945239,0.939634,0.936571,0.932208
2,0.961657,0.957427,0.953123,0.958319,0.956812,0.958656,0.949201,0.952863,0.951137,0.947506
3,0.957110,0.960940,0.957333,0.952014,0.943939,0.955191,0.946764,0.944938,0.942078,0.937381
4,0.899960,0.908882,0.909656,0.901662,0.906111,0.910355,0.900412,0.892240,0.902656,0.903156
Mean,0.929370,0.930635,0.927935,0.923996,0.925303,0.927904,0.920229,0.918759,0.917793,0.915923

In [6]:
tpot_res_file = 'out/tpot-lshs22.json'
dav_res_file = 'out/davidson-pipline-lshs22.json'

tpot_dict = json.load(open(tpot_res_file, "r"))
dav_dict = json.load(open(dav_res_file, "r"))

In [7]:
res_m_lst = []
for domain, _df, _res_dict in  prepare_dataframe(tpot_dict, 'TPOT', m_lst = ['F1-Macro']):
    res_m_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,TPOT.F1-M.Org,TPOT.F1-M.CF-0.1,TPOT.F1-M.CF-0.2,TPOT.F1-M.CF-0.3,TPOT.F1-M.CF-0.4,TPOT.F1-M.CF-0.5,TPOT.F1-M.CF-0.6,TPOT.F1-M.CF-0.7,TPOT.F1-M.CF-0.8,TPOT.F1-M.CF-0.9,TPOT.F1-M.CF-1.0
0,0.580932,0.555363,0.568701,0.564341,0.560286,0.541916,0.543037,0.557240,0.563013,0.562701,0.552251
1,0.602167,0.648972,0.649537,0.670313,0.653424,0.665292,0.654134,0.654851,0.593552,0.641117,0.637229
2,0.693939,0.675214,0.661059,0.672033,0.675311,0.680912,0.660848,0.667040,0.675728,0.650306,0.672746
3,0.665644,0.655520,0.655382,0.656977,0.655605,0.664799,0.651724,0.659300,0.655018,0.658445,0.657348
4,0.527061,0.539941,0.538554,0.535569,0.541836,0.537093,0.539660,0.543984,0.540867,0.543170,0.536288
Mean,0.613949,0.615002,0.614646,0.619847,0.617293,0.618002,0.609880,0.616483,0.605636,0.611148,0.611173

'Religion'

,TPOT.F1-M.Org,TPOT.F1-M.CF-0.1,TPOT.F1-M.CF-0.2,TPOT.F1-M.CF-0.3,TPOT.F1-M.CF-0.4,TPOT.F1-M.CF-0.5,TPOT.F1-M.CF-0.6,TPOT.F1-M.CF-0.7,TPOT.F1-M.CF-0.8,TPOT.F1-M.CF-0.9,TPOT.F1-M.CF-1.0
0,0.571848,0.554933,0.572053,0.546281,0.568311,0.524532,0.568855,0.538034,0.528888,0.541360,0.580516
1,0.680899,0.689752,0.661883,0.658854,0.684176,0.637036,0.652363,0.600210,0.625027,0.620578,0.640521
2,0.674293,0.648441,0.630249,0.659633,0.649743,0.640308,0.634725,0.621477,0.622670,0.591594,0.637054
3,0.709474,0.657223,0.674677,0.683308,0.629822,0.678232,0.628736,0.682497,0.654018,0.635065,0.650198
4,0.483007,0.483373,0.487738,0.461308,0.499425,0.509739,0.487866,0.489094,0.481430,0.470694,0.488785
Mean,0.623904,0.606745,0.605320,0.601877,0.606295,0.597969,0.594509,0.586263,0.582407,0.571858,0.599415

'Race'

,TPOT.F1-M.Org,TPOT.F1-M.CF-0.1,TPOT.F1-M.CF-0.2,TPOT.F1-M.CF-0.3,TPOT.F1-M.CF-0.4,TPOT.F1-M.CF-0.5,TPOT.F1-M.CF-0.6,TPOT.F1-M.CF-0.7,TPOT.F1-M.CF-0.8,TPOT.F1-M.CF-0.9,TPOT.F1-M.CF-1.0
0,0.577677,0.527291,0.550354,0.551456,0.500161,0.537954,0.544538,0.518786,0.532120,0.535480,0.531579
1,0.555295,0.545200,0.542088,0.537468,0.537428,0.540960,0.549513,0.550620,0.516723,0.544067,0.547943
2,0.572524,0.624000,0.641259,0.641714,0.657113,0.659730,0.647616,0.613922,0.634483,0.572470,0.656738
3,0.673416,0.616281,0.630240,0.590394,0.654116,0.641366,0.657060,0.639052,0.653364,0.582533,0.638980
4,0.526641,0.521240,0.553809,0.555812,0.530392,0.543631,0.525605,0.521974,0.545398,0.562770,0.537606
Mean,0.581111,0.566803,0.583550,0.575369,0.575842,0.584728,0.584867,0.568871,0.576417,0.559464,0.582569

'Politics'

,TPOT.F1-M.Org,TPOT.F1-M.CF-0.1,TPOT.F1-M.CF-0.2,TPOT.F1-M.CF-0.3,TPOT.F1-M.CF-0.4,TPOT.F1-M.CF-0.5,TPOT.F1-M.CF-0.6,TPOT.F1-M.CF-0.7,TPOT.F1-M.CF-0.8,TPOT.F1-M.CF-0.9,TPOT.F1-M.CF-1.0
0,0.523382,0.513844,0.528058,0.521241,0.512722,0.519016,0.520080,0.506379,0.511339,0.512458,0.485272
1,0.665626,0.654335,0.653683,0.645867,0.658281,0.654506,0.647278,0.681621,0.659281,0.646648,0.659359
2,0.684969,0.658295,0.670940,0.671909,0.652375,0.636035,0.656604,0.670082,0.686140,0.681661,0.637534
3,0.688921,0.691171,0.693941,0.689729,0.660669,0.691031,0.680319,0.672345,0.700329,0.695156,0.687161
4,0.572661,0.641137,0.647657,0.632427,0.641607,0.581912,0.633714,0.601797,0.588325,0.636904,0.618636
Mean,0.627112,0.631756,0.638856,0.632234,0.625131,0.616500,0.627599,0.626445,0.629083,0.634565,0.617592

'Sports'

,TPOT.F1-M.Org,TPOT.F1-M.CF-0.1,TPOT.F1-M.CF-0.2,TPOT.F1-M.CF-0.3,TPOT.F1-M.CF-0.4,TPOT.F1-M.CF-0.5,TPOT.F1-M.CF-0.6,TPOT.F1-M.CF-0.7,TPOT.F1-M.CF-0.8,TPOT.F1-M.CF-0.9,TPOT.F1-M.CF-1.0
0,0.533791,0.571649,0.540214,0.535440,0.559572,0.579031,0.604064,0.546146,0.547028,0.561617,0.544312
1,0.712412,0.679659,0.665693,0.665259,0.671454,0.663966,0.679628,0.659611,0.648232,0.644052,0.646746
2,0.706526,0.687137,0.676903,0.689232,0.678363,0.665254,0.692005,0.663730,0.679695,0.678192,0.656006
3,0.781087,0.738087,0.761417,0.773116,0.744338,0.757121,0.707213,0.726173,0.725359,0.772068,0.724358
4,0.680263,0.679670,0.683402,0.704655,0.703488,0.693377,0.683608,0.686436,0.699427,0.693646,0.707538
Mean,0.682816,0.671240,0.665526,0.673540,0.671443,0.671750,0.673304,0.656419,0.659948,0.669915,0.655792

In [8]:
res_w_lst = []
for domain, _df, _res_dict in  prepare_dataframe(tpot_dict, 'TPOT', m_lst = ['F1-Weighted']):
    res_w_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,TPOT.F1-W.Org,TPOT.F1-W.CF-0.1,TPOT.F1-W.CF-0.2,TPOT.F1-W.CF-0.3,TPOT.F1-W.CF-0.4,TPOT.F1-W.CF-0.5,TPOT.F1-W.CF-0.6,TPOT.F1-W.CF-0.7,TPOT.F1-W.CF-0.8,TPOT.F1-W.CF-0.9,TPOT.F1-W.CF-1.0
0,0.850752,0.847015,0.849100,0.852230,0.851390,0.835674,0.835085,0.850662,0.845300,0.845688,0.844437
1,0.881857,0.883041,0.879293,0.886728,0.882448,0.882605,0.883317,0.883960,0.875214,0.878479,0.874861
2,0.938223,0.935907,0.939893,0.934290,0.937682,0.941479,0.938143,0.929069,0.937900,0.928100,0.935044
3,0.940893,0.934410,0.932287,0.933633,0.934454,0.940332,0.929802,0.934739,0.932098,0.935441,0.935590
4,0.824074,0.841741,0.839562,0.835674,0.844694,0.837278,0.842303,0.848439,0.843953,0.847798,0.837558
Mean,0.887160,0.888423,0.888027,0.888511,0.890134,0.887473,0.885730,0.889374,0.886893,0.887101,0.885498

'Religion'

,TPOT.F1-W.Org,TPOT.F1-W.CF-0.1,TPOT.F1-W.CF-0.2,TPOT.F1-W.CF-0.3,TPOT.F1-W.CF-0.4,TPOT.F1-W.CF-0.5,TPOT.F1-W.CF-0.6,TPOT.F1-W.CF-0.7,TPOT.F1-W.CF-0.8,TPOT.F1-W.CF-0.9,TPOT.F1-W.CF-1.0
0,0.842798,0.836740,0.843114,0.836343,0.836766,0.829045,0.844664,0.834658,0.831640,0.832201,0.845735
1,0.910725,0.911481,0.905179,0.903026,0.909854,0.900967,0.906082,0.890775,0.892313,0.889334,0.903593
2,0.920321,0.915666,0.918080,0.916373,0.917864,0.912921,0.913212,0.903777,0.905285,0.899543,0.914845
3,0.934353,0.923870,0.929456,0.926485,0.917046,0.922232,0.924745,0.926757,0.925959,0.920772,0.923044
4,0.783745,0.783636,0.789976,0.772107,0.804610,0.819079,0.809706,0.792490,0.783346,0.786381,0.791871
Mean,0.878388,0.874279,0.877161,0.870867,0.877228,0.876849,0.879682,0.869691,0.867709,0.865646,0.875818

'Race'

,TPOT.F1-W.Org,TPOT.F1-W.CF-0.1,TPOT.F1-W.CF-0.2,TPOT.F1-W.CF-0.3,TPOT.F1-W.CF-0.4,TPOT.F1-W.CF-0.5,TPOT.F1-W.CF-0.6,TPOT.F1-W.CF-0.7,TPOT.F1-W.CF-0.8,TPOT.F1-W.CF-0.9,TPOT.F1-W.CF-1.0
0,0.892731,0.885174,0.888482,0.889640,0.871370,0.887308,0.887064,0.879377,0.883993,0.885334,0.887321
1,0.904391,0.899609,0.902287,0.894830,0.896727,0.902391,0.901404,0.902555,0.888177,0.899256,0.901202
2,0.893967,0.911853,0.916844,0.917855,0.916591,0.917717,0.916737,0.904774,0.913999,0.900497,0.918915
3,0.929156,0.921310,0.911959,0.911912,0.922354,0.922289,0.920654,0.918752,0.921586,0.910974,0.921033
4,0.760579,0.770228,0.763757,0.787798,0.752922,0.773160,0.751907,0.780418,0.768882,0.782303,0.772927
Mean,0.876165,0.877635,0.876666,0.880407,0.871993,0.880573,0.875553,0.877175,0.875327,0.875673,0.880280

'Politics'

,TPOT.F1-W.Org,TPOT.F1-W.CF-0.1,TPOT.F1-W.CF-0.2,TPOT.F1-W.CF-0.3,TPOT.F1-W.CF-0.4,TPOT.F1-W.CF-0.5,TPOT.F1-W.CF-0.6,TPOT.F1-W.CF-0.7,TPOT.F1-W.CF-0.8,TPOT.F1-W.CF-0.9,TPOT.F1-W.CF-1.0
0,0.776278,0.773500,0.774060,0.775629,0.778602,0.776799,0.776300,0.778228,0.777472,0.776573,0.768402
1,0.919089,0.913455,0.913662,0.917266,0.916717,0.914550,0.915243,0.917698,0.917216,0.911162,0.917036
2,0.919027,0.925033,0.928034,0.919297,0.927193,0.922348,0.922581,0.927032,0.923254,0.927252,0.915372
3,0.934619,0.942699,0.944197,0.940887,0.939504,0.941233,0.939213,0.941581,0.943868,0.938770,0.937468
4,0.840134,0.856397,0.856168,0.845447,0.862901,0.851720,0.863087,0.853229,0.846419,0.871331,0.864564
Mean,0.877829,0.882217,0.883224,0.879705,0.884983,0.881330,0.883285,0.883554,0.881646,0.885017,0.880569

'Sports'

,TPOT.F1-W.Org,TPOT.F1-W.CF-0.1,TPOT.F1-W.CF-0.2,TPOT.F1-W.CF-0.3,TPOT.F1-W.CF-0.4,TPOT.F1-W.CF-0.5,TPOT.F1-W.CF-0.6,TPOT.F1-W.CF-0.7,TPOT.F1-W.CF-0.8,TPOT.F1-W.CF-0.9,TPOT.F1-W.CF-1.0
0,0.874000,0.881274,0.878910,0.875599,0.884296,0.887472,0.890598,0.883433,0.883900,0.885837,0.882430
1,0.960462,0.959907,0.958565,0.958170,0.953263,0.957315,0.949191,0.953429,0.943582,0.950878,0.953252
2,0.964021,0.961258,0.960863,0.962230,0.961090,0.960054,0.962377,0.958766,0.962860,0.960098,0.952566
3,0.966177,0.959493,0.964739,0.961546,0.958184,0.958793,0.951305,0.958127,0.957363,0.963682,0.956513
4,0.897467,0.902329,0.904271,0.912647,0.910623,0.911696,0.907145,0.904158,0.912312,0.912599,0.915205
Mean,0.932425,0.932852,0.933470,0.934038,0.933491,0.935066,0.932123,0.931583,0.932003,0.934619,0.931993

In [9]:
_df_tpot = reduce(lambda x, y: pd.merge(pd.DataFrame(x), pd.DataFrame(y), on='Domain'), [res_m_lst, res_m_pj_lst, res_w_lst, res_w_pj_lst])
_df_tpot.columns = _df_tpot.columns.str.replace("TPOT.", "")
print('TPOT')
_df_tpot

TPOT

,Domain,$F1_M$,$F1_M.cf$,$F1_M.pj.cf$,$F1_W$,$F1_W.cf$,$F1_W.pj.cf$
0,Gender,0.614,0.620$_{cf=0.3}$,0.613$_{cf=0.1}$,0.887,0.890$_{cf=0.4}$,0.888$_{cf=0.1}$
1,Religion,0.624,0.607$_{cf=0.1}$,0.613$_{cf=0.5}$,0.878,0.880$_{cf=0.6}$,0.873$_{cf=0.6}$
2,Race,0.581,0.585$_{cf=0.6}$,0.590$_{cf=0.3}$,0.876,0.881$_{cf=0.5}$,0.887$_{cf=1.0}$
3,Politics,0.627,0.639$_{cf=0.2}$,0.631$_{cf=0.3}$,0.878,0.885$_{cf=0.9}$,0.880$_{cf=0.2}$
4,Sports,0.683,0.674$_{cf=0.3}$,0.674$_{cf=0.2}$,0.932,0.935$_{cf=0.5}$,0.931$_{cf=0.2}$

In [10]:
# _df_tpot = pd.merge(pd.DataFrame(res_m_lst), pd.DataFrame(res_w_lst), on='Domain')
# _df_tpot.columns = _df_tpot.columns.str.replace("TPOT.", "")
# print('TPOT')
# _df_tpot

In [11]:
res_m_pj_lst = []
for domain, _df, _res_dict in  prepare_dataframe(dav_pj_dict, 'Davd', m_lst = ['F1-Macro'], sota='pj.'):
    res_m_pj_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,Davd.F1-M.pj.CF-0.1,Davd.F1-M.pj.CF-0.2,Davd.F1-M.pj.CF-0.3,Davd.F1-M.pj.CF-0.4,Davd.F1-M.pj.CF-0.5,Davd.F1-M.pj.CF-0.6,Davd.F1-M.pj.CF-0.7,Davd.F1-M.pj.CF-0.8,Davd.F1-M.pj.CF-0.9,Davd.F1-M.pj.CF-1.0
0,0.568989,0.568731,0.574410,0.571951,0.569267,0.573613,0.570308,0.574794,0.575047,0.576022
1,0.681407,0.676495,0.679123,0.674165,0.668324,0.682946,0.675015,0.672615,0.678525,0.673337
2,0.675626,0.681706,0.675339,0.670591,0.668774,0.673221,0.663636,0.664324,0.675192,0.664013
3,0.765054,0.748684,0.758076,0.757005,0.762498,0.765926,0.753480,0.755438,0.757666,0.744968
4,0.552238,0.549434,0.551172,0.554595,0.556329,0.553704,0.553710,0.553670,0.550281,0.551153
Mean,0.648663,0.645010,0.647624,0.645661,0.645039,0.649882,0.643230,0.644168,0.647342,0.641899

'Religion'

,Davd.F1-M.pj.CF-0.1,Davd.F1-M.pj.CF-0.2,Davd.F1-M.pj.CF-0.3,Davd.F1-M.pj.CF-0.4,Davd.F1-M.pj.CF-0.5,Davd.F1-M.pj.CF-0.6,Davd.F1-M.pj.CF-0.7,Davd.F1-M.pj.CF-0.8,Davd.F1-M.pj.CF-0.9,Davd.F1-M.pj.CF-1.0
0,0.542359,0.543693,0.540194,0.550578,0.543663,0.535639,0.536027,0.542916,0.540994,0.541672
1,0.652522,0.649114,0.644621,0.657065,0.649423,0.652441,0.646662,0.642755,0.647805,0.634009
2,0.669353,0.666258,0.671846,0.673772,0.672409,0.671367,0.669736,0.671655,0.669805,0.665278
3,0.693672,0.693527,0.694804,0.701284,0.704253,0.708707,0.700393,0.701267,0.710881,0.714276
4,0.421124,0.428756,0.413680,0.412802,0.416353,0.427848,0.422856,0.432902,0.431266,0.427231
Mean,0.595806,0.596270,0.593029,0.599100,0.597220,0.599201,0.595135,0.598299,0.600150,0.596493

'Race'

,Davd.F1-M.pj.CF-0.1,Davd.F1-M.pj.CF-0.2,Davd.F1-M.pj.CF-0.3,Davd.F1-M.pj.CF-0.4,Davd.F1-M.pj.CF-0.5,Davd.F1-M.pj.CF-0.6,Davd.F1-M.pj.CF-0.7,Davd.F1-M.pj.CF-0.8,Davd.F1-M.pj.CF-0.9,Davd.F1-M.pj.CF-1.0
0,0.642769,0.642570,0.638557,0.641479,0.642609,0.637106,0.634176,0.640456,0.644986,0.634013
1,0.675237,0.672798,0.674477,0.669686,0.674742,0.676260,0.694933,0.686974,0.705630,0.690007
2,0.687368,0.674517,0.675027,0.684529,0.682950,0.688897,0.675806,0.671686,0.683475,0.674921
3,0.720881,0.724203,0.716604,0.718009,0.727333,0.718009,0.723126,0.727269,0.735325,0.735177
4,0.446158,0.451042,0.455144,0.455203,0.460463,0.457585,0.458886,0.461645,0.455467,0.461964
Mean,0.634483,0.633026,0.631962,0.633781,0.637620,0.635571,0.637386,0.637606,0.644977,0.639216

'Politics'

,Davd.F1-M.pj.CF-0.1,Davd.F1-M.pj.CF-0.2,Davd.F1-M.pj.CF-0.3,Davd.F1-M.pj.CF-0.4,Davd.F1-M.pj.CF-0.5,Davd.F1-M.pj.CF-0.6,Davd.F1-M.pj.CF-0.7,Davd.F1-M.pj.CF-0.8,Davd.F1-M.pj.CF-0.9,Davd.F1-M.pj.CF-1.0
0,0.526478,0.531189,0.535593,0.531969,0.535139,0.530620,0.532554,0.544251,0.533544,0.540699
1,0.685915,0.686223,0.685509,0.682943,0.684457,0.686791,0.676207,0.672387,0.677931,0.665515
2,0.671828,0.677082,0.675685,0.667977,0.665651,0.670948,0.669082,0.672389,0.678122,0.661901
3,0.749434,0.755317,0.756046,0.760242,0.771966,0.775158,0.766387,0.770344,0.765897,0.771684
4,0.591213,0.590464,0.595364,0.597463,0.601968,0.599744,0.595585,0.597244,0.612745,0.596214
Mean,0.644974,0.648055,0.649640,0.648119,0.651836,0.652652,0.647963,0.651323,0.653648,0.647203

'Sports'

,Davd.F1-M.pj.CF-0.1,Davd.F1-M.pj.CF-0.2,Davd.F1-M.pj.CF-0.3,Davd.F1-M.pj.CF-0.4,Davd.F1-M.pj.CF-0.5,Davd.F1-M.pj.CF-0.6,Davd.F1-M.pj.CF-0.7,Davd.F1-M.pj.CF-0.8,Davd.F1-M.pj.CF-0.9,Davd.F1-M.pj.CF-1.0
0,0.641107,0.619664,0.623382,0.614285,0.614014,0.606627,0.621889,0.613136,0.628020,0.612905
1,0.765335,0.766919,0.789771,0.788736,0.793289,0.765775,0.787291,0.786620,0.792285,0.799867
2,0.711409,0.709787,0.704486,0.718688,0.713331,0.722592,0.723895,0.721299,0.734277,0.707782
3,0.799121,0.800433,0.806881,0.801316,0.796601,0.807298,0.805583,0.814169,0.792800,0.807295
4,0.640965,0.645087,0.634526,0.639925,0.638156,0.636073,0.635007,0.632816,0.633230,0.630525
Mean,0.711587,0.708378,0.711809,0.712590,0.711078,0.707673,0.714733,0.713608,0.716122,0.711675

In [12]:
res_w_pj_lst = []
for domain, _df, _res_dict in  prepare_dataframe(dav_pj_dict, 'Davd', m_lst = ['F1-Weighted'], sota='pj.'):
    res_w_pj_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,Davd.F1-W.pj.CF-0.1,Davd.F1-W.pj.CF-0.2,Davd.F1-W.pj.CF-0.3,Davd.F1-W.pj.CF-0.4,Davd.F1-W.pj.CF-0.5,Davd.F1-W.pj.CF-0.6,Davd.F1-W.pj.CF-0.7,Davd.F1-W.pj.CF-0.8,Davd.F1-W.pj.CF-0.9,Davd.F1-W.pj.CF-1.0
0,0.838119,0.837150,0.839884,0.837027,0.836330,0.840047,0.837993,0.842917,0.843259,0.844342
1,0.896760,0.894467,0.895926,0.892016,0.892548,0.894780,0.892055,0.890232,0.893689,0.892261
2,0.931875,0.932446,0.929687,0.929816,0.930137,0.927947,0.924227,0.926091,0.925554,0.922799
3,0.953955,0.951095,0.952893,0.948987,0.949671,0.952093,0.946362,0.945176,0.942170,0.939827
4,0.785946,0.780626,0.781000,0.785538,0.784164,0.789345,0.789940,0.784985,0.779441,0.778960
Mean,0.881331,0.879157,0.879878,0.878677,0.878570,0.880843,0.878115,0.877880,0.876822,0.875638

'Religion'

,Davd.F1-W.pj.CF-0.1,Davd.F1-W.pj.CF-0.2,Davd.F1-W.pj.CF-0.3,Davd.F1-W.pj.CF-0.4,Davd.F1-W.pj.CF-0.5,Davd.F1-W.pj.CF-0.6,Davd.F1-W.pj.CF-0.7,Davd.F1-W.pj.CF-0.8,Davd.F1-W.pj.CF-0.9,Davd.F1-W.pj.CF-1.0
0,0.832148,0.833555,0.832265,0.835805,0.831247,0.828213,0.827789,0.830050,0.829406,0.829894
1,0.895373,0.895054,0.894192,0.896295,0.892330,0.895486,0.893951,0.892282,0.887875,0.887224
2,0.898104,0.897751,0.899445,0.902188,0.900712,0.900486,0.898509,0.899771,0.896966,0.896264
3,0.931533,0.934619,0.937716,0.940561,0.941150,0.943537,0.941695,0.941977,0.942419,0.943794
4,0.641384,0.643579,0.640585,0.649836,0.644538,0.651449,0.653863,0.659441,0.661352,0.656779
Mean,0.839708,0.840912,0.840841,0.844937,0.841995,0.843834,0.843161,0.844704,0.843603,0.842791

'Race'

,Davd.F1-W.pj.CF-0.1,Davd.F1-W.pj.CF-0.2,Davd.F1-W.pj.CF-0.3,Davd.F1-W.pj.CF-0.4,Davd.F1-W.pj.CF-0.5,Davd.F1-W.pj.CF-0.6,Davd.F1-W.pj.CF-0.7,Davd.F1-W.pj.CF-0.8,Davd.F1-W.pj.CF-0.9,Davd.F1-W.pj.CF-1.0
0,0.909937,0.909843,0.909717,0.909705,0.910214,0.908924,0.908751,0.908804,0.910372,0.909749
1,0.933948,0.931957,0.934206,0.931702,0.934324,0.932930,0.937794,0.936663,0.941053,0.937080
2,0.935917,0.934259,0.934220,0.934032,0.934973,0.935174,0.931365,0.930711,0.935106,0.931758
3,0.942661,0.942437,0.942818,0.942870,0.943534,0.942870,0.942543,0.942326,0.945388,0.944548
4,0.609642,0.610576,0.612577,0.611614,0.620542,0.618129,0.620133,0.621849,0.620824,0.622546
Mean,0.866421,0.865814,0.866707,0.865985,0.868717,0.867605,0.868117,0.868071,0.870549,0.869136

'Politics'

,Davd.F1-W.pj.CF-0.1,Davd.F1-W.pj.CF-0.2,Davd.F1-W.pj.CF-0.3,Davd.F1-W.pj.CF-0.4,Davd.F1-W.pj.CF-0.5,Davd.F1-W.pj.CF-0.6,Davd.F1-W.pj.CF-0.7,Davd.F1-W.pj.CF-0.8,Davd.F1-W.pj.CF-0.9,Davd.F1-W.pj.CF-1.0
0,0.779115,0.783867,0.787067,0.783368,0.785226,0.783626,0.782487,0.788691,0.784649,0.790760
1,0.901088,0.902532,0.904580,0.901679,0.904496,0.902599,0.904360,0.902392,0.903617,0.900265
2,0.903519,0.903524,0.903006,0.898743,0.896261,0.897346,0.896513,0.896135,0.897546,0.889652
3,0.932028,0.937109,0.938164,0.940222,0.943706,0.944846,0.943363,0.943332,0.943373,0.944268
4,0.790245,0.791177,0.798425,0.799259,0.797857,0.800719,0.797375,0.796905,0.809223,0.801727
Mean,0.861199,0.863642,0.866248,0.864654,0.865509,0.865827,0.864819,0.865491,0.867682,0.865334

'Sports'

,Davd.F1-W.pj.CF-0.1,Davd.F1-W.pj.CF-0.2,Davd.F1-W.pj.CF-0.3,Davd.F1-W.pj.CF-0.4,Davd.F1-W.pj.CF-0.5,Davd.F1-W.pj.CF-0.6,Davd.F1-W.pj.CF-0.7,Davd.F1-W.pj.CF-0.8,Davd.F1-W.pj.CF-0.9,Davd.F1-W.pj.CF-1.0
0,0.895635,0.892929,0.894305,0.892887,0.892234,0.890703,0.893030,0.892912,0.895261,0.894544
1,0.961655,0.962734,0.963586,0.963720,0.966133,0.961404,0.963704,0.963139,0.964015,0.963863
2,0.954348,0.953326,0.952523,0.955973,0.955362,0.956496,0.957295,0.954592,0.957725,0.954588
3,0.964170,0.964771,0.963854,0.963277,0.962484,0.963452,0.963620,0.967310,0.963606,0.963009
4,0.869699,0.872327,0.866252,0.869725,0.868560,0.865503,0.863884,0.864714,0.864275,0.861230
Mean,0.929102,0.929217,0.928104,0.929116,0.928954,0.927512,0.928307,0.928534,0.928976,0.927447

In [13]:
res_m_lst = []
for domain, _df, _res_dict in  prepare_dataframe(dav_dict, 'Davd', m_lst = ['F1-Macro']):
    res_m_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,Davd.F1-M.Org,Davd.F1-M.CF-0.1,Davd.F1-M.CF-0.2,Davd.F1-M.CF-0.3,Davd.F1-M.CF-0.4,Davd.F1-M.CF-0.5,Davd.F1-M.CF-0.6,Davd.F1-M.CF-0.7,Davd.F1-M.CF-0.8,Davd.F1-M.CF-0.9,Davd.F1-M.CF-1.0
0,0.569494,0.571005,0.573977,0.570086,0.569962,0.571818,0.575395,0.569324,0.573114,0.572060,0.571451
1,0.679806,0.672438,0.675379,0.680700,0.687470,0.682262,0.686799,0.683438,0.677267,0.678670,0.678028
2,0.673200,0.677282,0.677174,0.689586,0.685432,0.681907,0.676631,0.686971,0.675030,0.682449,0.680160
3,0.764484,0.767525,0.771370,0.766829,0.751677,0.761086,0.765602,0.763231,0.765954,0.770444,0.768577
4,0.556670,0.549433,0.553042,0.554743,0.548753,0.561821,0.558728,0.561070,0.566345,0.569759,0.569363
Mean,0.648731,0.647537,0.650188,0.652389,0.648659,0.651779,0.652631,0.652807,0.651542,0.654676,0.653516

'Religion'

,Davd.F1-M.Org,Davd.F1-M.CF-0.1,Davd.F1-M.CF-0.2,Davd.F1-M.CF-0.3,Davd.F1-M.CF-0.4,Davd.F1-M.CF-0.5,Davd.F1-M.CF-0.6,Davd.F1-M.CF-0.7,Davd.F1-M.CF-0.8,Davd.F1-M.CF-0.9,Davd.F1-M.CF-1.0
0,0.542027,0.544562,0.544166,0.546051,0.551366,0.547235,0.543914,0.551327,0.554111,0.554414,0.553711
1,0.658984,0.658315,0.654905,0.656121,0.658160,0.648724,0.656238,0.662479,0.658082,0.656960,0.659367
2,0.661752,0.666582,0.674527,0.676122,0.670962,0.679183,0.679455,0.673537,0.672031,0.672300,0.678539
3,0.689489,0.699326,0.690629,0.685815,0.702098,0.699345,0.703946,0.703069,0.702623,0.699989,0.699989
4,0.422311,0.430733,0.416681,0.433873,0.435251,0.431107,0.437919,0.437213,0.434500,0.432108,0.433914
Mean,0.594913,0.599904,0.596182,0.599596,0.603568,0.601119,0.604295,0.605525,0.604269,0.603154,0.605104

'Race'

,Davd.F1-M.Org,Davd.F1-M.CF-0.1,Davd.F1-M.CF-0.2,Davd.F1-M.CF-0.3,Davd.F1-M.CF-0.4,Davd.F1-M.CF-0.5,Davd.F1-M.CF-0.6,Davd.F1-M.CF-0.7,Davd.F1-M.CF-0.8,Davd.F1-M.CF-0.9,Davd.F1-M.CF-1.0
0,0.641635,0.641447,0.649026,0.651235,0.639540,0.637039,0.640647,0.638616,0.634093,0.632779,0.629448
1,0.680793,0.680066,0.684033,0.679228,0.673506,0.680280,0.689484,0.682185,0.675692,0.686872,0.693722
2,0.672120,0.676337,0.676809,0.672797,0.674307,0.680273,0.680820,0.682061,0.670971,0.673712,0.685140
3,0.718174,0.719110,0.715573,0.724994,0.718186,0.729129,0.724667,0.726658,0.738467,0.739448,0.736397
4,0.452728,0.450895,0.450739,0.457723,0.453866,0.454397,0.456833,0.461791,0.449862,0.459943,0.450464
Mean,0.633090,0.633571,0.635236,0.637195,0.631881,0.636224,0.638490,0.638262,0.633817,0.638551,0.639034

'Politics'

,Davd.F1-M.Org,Davd.F1-M.CF-0.1,Davd.F1-M.CF-0.2,Davd.F1-M.CF-0.3,Davd.F1-M.CF-0.4,Davd.F1-M.CF-0.5,Davd.F1-M.CF-0.6,Davd.F1-M.CF-0.7,Davd.F1-M.CF-0.8,Davd.F1-M.CF-0.9,Davd.F1-M.CF-1.0
0,0.526485,0.521532,0.529839,0.527336,0.528753,0.527972,0.530249,0.533192,0.528845,0.530306,0.528586
1,0.691844,0.688630,0.688226,0.701413,0.682886,0.684534,0.697516,0.691954,0.688691,0.691038,0.691750
2,0.671975,0.675811,0.674845,0.678274,0.677889,0.678832,0.680516,0.683442,0.686065,0.687012,0.688188
3,0.740431,0.745771,0.751173,0.753788,0.751684,0.749565,0.755210,0.745584,0.755322,0.762005,0.762508
4,0.582353,0.588405,0.589311,0.601153,0.590840,0.599956,0.604188,0.602561,0.599955,0.611292,0.607567
Mean,0.642618,0.644030,0.646679,0.652393,0.646410,0.648172,0.653536,0.651347,0.651776,0.656331,0.655720

'Sports'

,Davd.F1-M.Org,Davd.F1-M.CF-0.1,Davd.F1-M.CF-0.2,Davd.F1-M.CF-0.3,Davd.F1-M.CF-0.4,Davd.F1-M.CF-0.5,Davd.F1-M.CF-0.6,Davd.F1-M.CF-0.7,Davd.F1-M.CF-0.8,Davd.F1-M.CF-0.9,Davd.F1-M.CF-1.0
0,0.636063,0.635225,0.618704,0.634226,0.632721,0.615231,0.622652,0.613676,0.612385,0.609275,0.609943
1,0.761083,0.761083,0.762474,0.765264,0.759878,0.759664,0.766945,0.765710,0.764699,0.773710,0.767595
2,0.714771,0.710962,0.709006,0.707001,0.719388,0.723023,0.720965,0.710469,0.714195,0.726026,0.723772
3,0.795966,0.798737,0.802628,0.813107,0.806334,0.817754,0.814036,0.818238,0.800153,0.816701,0.815410
4,0.641662,0.643235,0.643831,0.643412,0.645625,0.647576,0.647263,0.649785,0.649015,0.653356,0.651997
Mean,0.709909,0.709848,0.707329,0.712602,0.712789,0.712650,0.714372,0.711576,0.708089,0.715813,0.713743

In [14]:
res_w_lst = []
for domain, _df, _res_dict in  prepare_dataframe(dav_dict, 'Davd', m_lst = ['F1-Weighted']):
    res_w_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,Davd.F1-W.Org,Davd.F1-W.CF-0.1,Davd.F1-W.CF-0.2,Davd.F1-W.CF-0.3,Davd.F1-W.CF-0.4,Davd.F1-W.CF-0.5,Davd.F1-W.CF-0.6,Davd.F1-W.CF-0.7,Davd.F1-W.CF-0.8,Davd.F1-W.CF-0.9,Davd.F1-W.CF-1.0
0,0.838297,0.837986,0.839898,0.837531,0.838571,0.840506,0.840394,0.838990,0.839914,0.841918,0.841189
1,0.897389,0.896145,0.895848,0.896521,0.898729,0.898481,0.900190,0.898515,0.896188,0.898118,0.897518
2,0.931402,0.935888,0.933283,0.935027,0.932763,0.935104,0.932996,0.933923,0.933402,0.933647,0.934873
3,0.956591,0.955556,0.956279,0.953550,0.953533,0.954053,0.950775,0.951952,0.952897,0.952417,0.951533
4,0.786425,0.784095,0.788234,0.785289,0.785494,0.792578,0.789998,0.792197,0.794865,0.798023,0.797072
Mean,0.882021,0.881934,0.882708,0.881584,0.881818,0.884144,0.882871,0.883115,0.883453,0.884825,0.884437

'Religion'

,Davd.F1-W.Org,Davd.F1-W.CF-0.1,Davd.F1-W.CF-0.2,Davd.F1-W.CF-0.3,Davd.F1-W.CF-0.4,Davd.F1-W.CF-0.5,Davd.F1-W.CF-0.6,Davd.F1-W.CF-0.7,Davd.F1-W.CF-0.8,Davd.F1-W.CF-0.9,Davd.F1-W.CF-1.0
0,0.832525,0.833749,0.833307,0.834613,0.837550,0.834465,0.833567,0.836275,0.838274,0.838867,0.838008
1,0.897330,0.898218,0.897061,0.898080,0.898707,0.897686,0.899724,0.901749,0.900564,0.900689,0.900450
2,0.896984,0.897558,0.903181,0.902526,0.902789,0.904997,0.905419,0.902987,0.902609,0.903731,0.907555
3,0.925929,0.927936,0.929114,0.932057,0.937041,0.939150,0.940642,0.939204,0.940574,0.941466,0.941466
4,0.639077,0.641446,0.643288,0.646315,0.654551,0.655176,0.661061,0.664994,0.661564,0.667685,0.670656
Mean,0.838369,0.839781,0.841190,0.842718,0.846127,0.846295,0.848083,0.849042,0.848717,0.850488,0.851627

'Race'

,Davd.F1-W.Org,Davd.F1-W.CF-0.1,Davd.F1-W.CF-0.2,Davd.F1-W.CF-0.3,Davd.F1-W.CF-0.4,Davd.F1-W.CF-0.5,Davd.F1-W.CF-0.6,Davd.F1-W.CF-0.7,Davd.F1-W.CF-0.8,Davd.F1-W.CF-0.9,Davd.F1-W.CF-1.0
0,0.910117,0.910023,0.913061,0.912680,0.909498,0.907868,0.909640,0.909249,0.908700,0.909729,0.907528
1,0.933181,0.934175,0.935337,0.934720,0.935500,0.937023,0.939447,0.937102,0.937068,0.938725,0.940408
2,0.933430,0.935341,0.935344,0.933381,0.934083,0.934473,0.934624,0.933611,0.932581,0.933842,0.936340
3,0.939505,0.940182,0.941381,0.943234,0.942921,0.944976,0.941780,0.943555,0.947741,0.945974,0.946103
4,0.606357,0.605188,0.608273,0.610921,0.611215,0.613409,0.616905,0.615818,0.617899,0.620122,0.620237
Mean,0.864518,0.864982,0.866679,0.866987,0.866644,0.867550,0.868479,0.867867,0.868798,0.869678,0.870123

'Politics'

,Davd.F1-W.Org,Davd.F1-W.CF-0.1,Davd.F1-W.CF-0.2,Davd.F1-W.CF-0.3,Davd.F1-W.CF-0.4,Davd.F1-W.CF-0.5,Davd.F1-W.CF-0.6,Davd.F1-W.CF-0.7,Davd.F1-W.CF-0.8,Davd.F1-W.CF-0.9,Davd.F1-W.CF-1.0
0,0.782063,0.780474,0.783057,0.783343,0.782448,0.783565,0.782171,0.781962,0.781392,0.781930,0.781182
1,0.902623,0.903680,0.907034,0.909615,0.904869,0.908688,0.911734,0.910509,0.912104,0.912035,0.912498
2,0.905087,0.906338,0.906600,0.907423,0.908528,0.908841,0.909002,0.910552,0.912792,0.913506,0.914188
3,0.929081,0.933392,0.934527,0.941087,0.941181,0.942496,0.942343,0.940566,0.944174,0.943776,0.944684
4,0.780896,0.789932,0.793177,0.798338,0.796923,0.803170,0.805845,0.804604,0.808617,0.809735,0.811352
Mean,0.859950,0.862763,0.864879,0.867961,0.866790,0.869352,0.870219,0.869639,0.871816,0.872197,0.872781

'Sports'

,Davd.F1-W.Org,Davd.F1-W.CF-0.1,Davd.F1-W.CF-0.2,Davd.F1-W.CF-0.3,Davd.F1-W.CF-0.4,Davd.F1-W.CF-0.5,Davd.F1-W.CF-0.6,Davd.F1-W.CF-0.7,Davd.F1-W.CF-0.8,Davd.F1-W.CF-0.9,Davd.F1-W.CF-1.0
0,0.894851,0.894989,0.895015,0.895955,0.895585,0.895007,0.895458,0.895180,0.894822,0.893334,0.893842
1,0.962925,0.962925,0.963143,0.962407,0.962107,0.963008,0.965397,0.965133,0.965615,0.965149,0.964859
2,0.954146,0.954128,0.954865,0.953453,0.958754,0.960260,0.958873,0.956300,0.957466,0.960151,0.959800
3,0.965327,0.965499,0.966439,0.968682,0.968328,0.970522,0.972208,0.972245,0.970708,0.973321,0.973431
4,0.869296,0.871662,0.872270,0.872387,0.874844,0.876686,0.876701,0.876680,0.877836,0.879833,0.879363
Mean,0.929309,0.929841,0.930347,0.930577,0.931923,0.933096,0.933727,0.933107,0.933289,0.934358,0.934259

In [15]:
_df_davd = reduce(lambda x, y: pd.merge(pd.DataFrame(x), pd.DataFrame(y), on='Domain'), [res_m_lst, res_m_pj_lst, res_w_lst, res_w_pj_lst])
_df_davd.columns = _df_davd.columns.str.replace("Davd.", "")
print('Davd')
_df_davd

Davd

,Domain,$F1_M$,$F1_M.cf$,$F1_M.pj.cf$,$F1_W$,$F1_W.cf$,$F1_W.pj.cf$
0,Gender,0.649,0.655$_{cf=0.9}$,0.650$_{cf=0.6}$,0.882,0.885$_{cf=0.9}$,0.881$_{cf=0.1}$
1,Religion,0.595,0.606$_{cf=0.7}$,0.600$_{cf=0.9}$,0.838,0.852$_{cf=1.0}$,0.845$_{cf=0.4}$
2,Race,0.633,0.639$_{cf=1.0}$,0.645$_{cf=0.9}$,0.865,0.870$_{cf=1.0}$,0.871$_{cf=0.9}$
3,Politics,0.643,0.656$_{cf=0.9}$,0.654$_{cf=0.9}$,0.860,0.873$_{cf=1.0}$,0.868$_{cf=0.9}$
4,Sports,0.710,0.716$_{cf=0.9}$,0.716$_{cf=0.9}$,0.929,0.934$_{cf=0.9}$,0.929$_{cf=0.2}$

In [16]:
# _df_davd = pd.merge(pd.DataFrame(res_m_lst), pd.DataFrame(res_w_lst), on='Domain')
# _df_davd.columns = _df_davd.columns.str.replace("Davd.", "")
# print('Davd')
# _df_davd

In [17]:
bert_res_pj_file = 'out/bert-base-uncased-EP_5-ft-lshd22-pj.json'
bert_pj_dict = json.load(open(bert_res_pj_file, "r"))

res_m_pj_lst = []
for domain, _df, _res_dict in  prepare_dataframe(bert_pj_dict, 'BERT', m_lst = ['F1-Macro'], sota='pj.'):
    res_m_pj_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,BERT.F1-M.pj.CF-0.1,BERT.F1-M.pj.CF-0.2,BERT.F1-M.pj.CF-0.3,BERT.F1-M.pj.CF-0.4,BERT.F1-M.pj.CF-0.5,BERT.F1-M.pj.CF-0.6,BERT.F1-M.pj.CF-0.7,BERT.F1-M.pj.CF-0.8,BERT.F1-M.pj.CF-0.9,BERT.F1-M.pj.CF-1.0
0,0.714984,0.720855,0.688653,0.737935,0.697791,0.721493,0.729588,0.704110,0.742416,0.749751
1,0.784024,0.744355,0.792956,0.747330,0.778432,0.759511,0.780303,0.675607,0.768193,0.752157
2,0.871592,0.782046,0.842021,0.835173,0.806433,0.827951,0.860859,0.824531,0.709565,0.831568
3,0.753485,0.804028,0.779400,0.731568,0.764565,0.777380,0.801354,0.832010,0.817124,0.806555
4,0.655216,0.636716,0.698533,0.645727,0.656877,0.638249,0.664035,0.628331,0.671143,0.625251
Mean,0.755860,0.737600,0.760313,0.739547,0.740820,0.744917,0.767228,0.732918,0.741688,0.753057

'Religion'

,BERT.F1-M.pj.CF-0.1,BERT.F1-M.pj.CF-0.2,BERT.F1-M.pj.CF-0.3,BERT.F1-M.pj.CF-0.4,BERT.F1-M.pj.CF-0.5,BERT.F1-M.pj.CF-0.6,BERT.F1-M.pj.CF-0.7,BERT.F1-M.pj.CF-0.8,BERT.F1-M.pj.CF-0.9,BERT.F1-M.pj.CF-1.0
0,0.700368,0.651163,0.697313,0.635526,0.691092,0.619815,0.665554,0.678902,0.656555,0.694315
1,0.784878,0.731352,0.765127,0.764654,0.763023,0.753404,0.802443,0.755399,0.719700,0.770493
2,0.708154,0.732070,0.757115,0.772568,0.722634,0.751555,0.732415,0.733306,0.725873,0.704340
3,0.819275,0.779792,0.807467,0.829466,0.803999,0.761351,0.769323,0.785359,0.818704,0.802707
4,0.579879,0.519210,0.648790,0.690983,0.648006,0.726127,0.649814,0.479997,0.669709,0.711111
Mean,0.718511,0.682717,0.735162,0.738639,0.725751,0.722450,0.723910,0.686593,0.718108,0.736593

'Race'

,BERT.F1-M.pj.CF-0.1,BERT.F1-M.pj.CF-0.2,BERT.F1-M.pj.CF-0.3,BERT.F1-M.pj.CF-0.4,BERT.F1-M.pj.CF-0.5,BERT.F1-M.pj.CF-0.6,BERT.F1-M.pj.CF-0.7,BERT.F1-M.pj.CF-0.8,BERT.F1-M.pj.CF-0.9,BERT.F1-M.pj.CF-1.0
0,0.672490,0.676688,0.665412,0.671411,0.664679,0.681679,0.621095,0.692355,0.631720,0.654221
1,0.732792,0.701751,0.655773,0.755386,0.686821,0.721977,0.732319,0.743532,0.727842,0.727549
2,0.757824,0.791045,0.792257,0.796199,0.814054,0.768747,0.762151,0.783239,0.768507,0.772006
3,0.787832,0.813462,0.833225,0.763550,0.764555,0.767831,0.749541,0.793484,0.714043,0.768749
4,0.517033,0.559045,0.529383,0.589464,0.617552,0.590341,0.607732,0.611987,0.621648,0.598899
Mean,0.693594,0.708398,0.695210,0.715202,0.709532,0.706115,0.694568,0.724919,0.692752,0.704285

'Politics'

,BERT.F1-M.pj.CF-0.1,BERT.F1-M.pj.CF-0.2,BERT.F1-M.pj.CF-0.3,BERT.F1-M.pj.CF-0.4,BERT.F1-M.pj.CF-0.5,BERT.F1-M.pj.CF-0.6,BERT.F1-M.pj.CF-0.7,BERT.F1-M.pj.CF-0.8,BERT.F1-M.pj.CF-0.9,BERT.F1-M.pj.CF-1.0
0,0.661975,0.685961,0.669197,0.673935,0.671816,0.647052,0.675442,0.622033,0.703452,0.651363
1,0.818697,0.789375,0.742813,0.810567,0.771647,0.809654,0.773463,0.766723,0.736102,0.767120
2,0.807790,0.781621,0.753004,0.781479,0.697987,0.806660,0.799123,0.772781,0.772903,0.742293
3,0.795341,0.807506,0.788787,0.751173,0.786818,0.833587,0.844290,0.827845,0.830794,0.821524
4,0.714686,0.779557,0.752625,0.713915,0.684116,0.724514,0.728799,0.690122,0.753383,0.708145
Mean,0.759698,0.768804,0.741285,0.746214,0.722477,0.764293,0.764223,0.735901,0.759327,0.738089

'Sports'

,BERT.F1-M.pj.CF-0.1,BERT.F1-M.pj.CF-0.2,BERT.F1-M.pj.CF-0.3,BERT.F1-M.pj.CF-0.4,BERT.F1-M.pj.CF-0.5,BERT.F1-M.pj.CF-0.6,BERT.F1-M.pj.CF-0.7,BERT.F1-M.pj.CF-0.8,BERT.F1-M.pj.CF-0.9,BERT.F1-M.pj.CF-1.0
0,0.629009,0.603085,0.619615,0.667682,0.669985,0.629748,0.619346,0.650504,0.662346,0.641017
1,0.808470,0.778925,0.723848,0.799842,0.790359,0.739486,0.793998,0.740436,0.808344,0.770953
2,0.776872,0.766933,0.810421,0.759434,0.771423,0.754159,0.731478,0.747466,0.741174,0.708205
3,0.904022,0.862644,0.895250,0.876287,0.895772,0.904581,0.850874,0.824744,0.862917,0.862157
4,0.745266,0.740127,0.736704,0.753528,0.757766,0.737332,0.701668,0.723761,0.751230,0.748062
Mean,0.772728,0.750343,0.757168,0.771355,0.777061,0.753061,0.739473,0.737382,0.765202,0.746079

In [18]:
res_w_pj_lst = []
for domain, _df, _res_dict in  prepare_dataframe(bert_pj_dict, 'BERT', m_lst = ['F1-Weighted'], sota='pj.'):
    res_w_pj_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,BERT.F1-W.pj.CF-0.1,BERT.F1-W.pj.CF-0.2,BERT.F1-W.pj.CF-0.3,BERT.F1-W.pj.CF-0.4,BERT.F1-W.pj.CF-0.5,BERT.F1-W.pj.CF-0.6,BERT.F1-W.pj.CF-0.7,BERT.F1-W.pj.CF-0.8,BERT.F1-W.pj.CF-0.9,BERT.F1-W.pj.CF-1.0
0,0.914054,0.913976,0.885784,0.906489,0.886690,0.882864,0.907923,0.884874,0.898444,0.899106
1,0.942699,0.925528,0.929382,0.928798,0.929625,0.910206,0.931387,0.883594,0.927603,0.929237
2,0.960746,0.945691,0.953858,0.939478,0.944806,0.952022,0.950900,0.941580,0.910817,0.949896
3,0.937670,0.945422,0.939349,0.924685,0.933710,0.936503,0.933099,0.949624,0.948101,0.936979
4,0.820653,0.823983,0.855594,0.807968,0.831140,0.805183,0.833286,0.817544,0.841955,0.835577
Mean,0.915165,0.910920,0.912793,0.901484,0.905194,0.897356,0.911319,0.895443,0.905384,0.910159

'Religion'

,BERT.F1-W.pj.CF-0.1,BERT.F1-W.pj.CF-0.2,BERT.F1-W.pj.CF-0.3,BERT.F1-W.pj.CF-0.4,BERT.F1-W.pj.CF-0.5,BERT.F1-W.pj.CF-0.6,BERT.F1-W.pj.CF-0.7,BERT.F1-W.pj.CF-0.8,BERT.F1-W.pj.CF-0.9,BERT.F1-W.pj.CF-1.0
0,0.901388,0.893111,0.900290,0.884746,0.895447,0.876748,0.894194,0.890034,0.872654,0.902374
1,0.937020,0.926157,0.930835,0.929701,0.931756,0.922831,0.932003,0.921825,0.925121,0.939086
2,0.951048,0.933387,0.944303,0.947853,0.940921,0.937098,0.930309,0.940409,0.933902,0.932425
3,0.957639,0.954548,0.956615,0.958408,0.953194,0.954532,0.946109,0.954374,0.950401,0.952203
4,0.832576,0.814435,0.831468,0.844694,0.822754,0.877703,0.833460,0.798917,0.872263,0.860819
Mean,0.915934,0.904328,0.912702,0.913080,0.908814,0.913782,0.907215,0.901112,0.910868,0.917381

'Race'

,BERT.F1-W.pj.CF-0.1,BERT.F1-W.pj.CF-0.2,BERT.F1-W.pj.CF-0.3,BERT.F1-W.pj.CF-0.4,BERT.F1-W.pj.CF-0.5,BERT.F1-W.pj.CF-0.6,BERT.F1-W.pj.CF-0.7,BERT.F1-W.pj.CF-0.8,BERT.F1-W.pj.CF-0.9,BERT.F1-W.pj.CF-1.0
0,0.932952,0.930198,0.929668,0.928443,0.927248,0.933982,0.914149,0.927557,0.926460,0.926706
1,0.948220,0.942693,0.937334,0.952455,0.942761,0.948786,0.948376,0.950070,0.947307,0.945117
2,0.949375,0.957521,0.957854,0.959840,0.955778,0.952561,0.945013,0.955609,0.950400,0.949491
3,0.954068,0.955462,0.958337,0.948200,0.948377,0.952045,0.944576,0.953611,0.938529,0.948821
4,0.714175,0.751554,0.740879,0.739496,0.780525,0.791814,0.763711,0.789162,0.812914,0.803224
Mean,0.899758,0.907485,0.904815,0.905687,0.910938,0.915838,0.903165,0.915202,0.915122,0.914672

'Politics'

,BERT.F1-W.pj.CF-0.1,BERT.F1-W.pj.CF-0.2,BERT.F1-W.pj.CF-0.3,BERT.F1-W.pj.CF-0.4,BERT.F1-W.pj.CF-0.5,BERT.F1-W.pj.CF-0.6,BERT.F1-W.pj.CF-0.7,BERT.F1-W.pj.CF-0.8,BERT.F1-W.pj.CF-0.9,BERT.F1-W.pj.CF-1.0
0,0.849468,0.861042,0.860872,0.866675,0.859058,0.827902,0.853530,0.813856,0.872342,0.843472
1,0.939201,0.937368,0.918047,0.924247,0.927575,0.940293,0.922531,0.916005,0.916234,0.915276
2,0.937375,0.926695,0.926072,0.928686,0.925502,0.925552,0.923806,0.932048,0.922170,0.919955
3,0.946343,0.939215,0.942913,0.939872,0.944411,0.947187,0.946356,0.942482,0.949258,0.945961
4,0.855727,0.890095,0.879912,0.851044,0.847766,0.866036,0.874543,0.864653,0.868629,0.847737
Mean,0.905623,0.910883,0.905563,0.902105,0.900863,0.901394,0.904153,0.893809,0.905727,0.894480

'Sports'

,BERT.F1-W.pj.CF-0.1,BERT.F1-W.pj.CF-0.2,BERT.F1-W.pj.CF-0.3,BERT.F1-W.pj.CF-0.4,BERT.F1-W.pj.CF-0.5,BERT.F1-W.pj.CF-0.6,BERT.F1-W.pj.CF-0.7,BERT.F1-W.pj.CF-0.8,BERT.F1-W.pj.CF-0.9,BERT.F1-W.pj.CF-1.0
0,0.914300,0.911065,0.904930,0.915335,0.911797,0.910065,0.903915,0.905248,0.913061,0.897820
1,0.968461,0.949647,0.960600,0.960258,0.965601,0.950965,0.962084,0.955456,0.968125,0.959339
2,0.969624,0.966174,0.970827,0.965023,0.963411,0.963879,0.958412,0.953109,0.956628,0.955697
3,0.981088,0.972073,0.980952,0.969680,0.978543,0.978900,0.974578,0.963721,0.976285,0.967049
4,0.910067,0.910464,0.906893,0.896952,0.916971,0.893031,0.897933,0.906755,0.906268,0.899091
Mean,0.948708,0.941885,0.944841,0.941449,0.947265,0.939368,0.939384,0.936858,0.944073,0.935799

In [19]:
bert_res_file = 'out/bert-base-uncased-EP_5-ft-lshd22.json'
bert_dict = json.load(open(bert_res_file, "r"))

res_m_lst = []
for domain, _df, _res_dict in  prepare_dataframe(bert_dict, 'BERT', m_lst = ['F1-Macro']):
    res_m_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,BERT.F1-M.Org,BERT.F1-M.CF-0.1,BERT.F1-M.CF-0.2,BERT.F1-M.CF-0.3,BERT.F1-M.CF-0.4,BERT.F1-M.CF-0.5,BERT.F1-M.CF-0.6,BERT.F1-M.CF-0.7,BERT.F1-M.CF-0.8,BERT.F1-M.CF-0.9,BERT.F1-M.CF-1.0
0,0.738722,0.737940,0.755189,0.752714,0.702723,0.703905,0.698370,0.750859,0.729129,0.722520,0.720348
1,0.777631,0.796363,0.776790,0.769553,0.789581,0.772583,0.773159,0.791330,0.771038,0.743940,0.777394
2,0.842910,0.805278,0.847542,0.820653,0.865757,0.821853,0.825408,0.804795,0.824740,0.867090,0.852926
3,0.808594,0.802291,0.777254,0.845497,0.835557,0.823306,0.798303,0.777741,0.826472,0.808639,0.807314
4,0.683365,0.642123,0.706020,0.603642,0.711113,0.677197,0.659149,0.666681,0.657007,0.681889,0.671405
Mean,0.770245,0.756799,0.772559,0.758412,0.780946,0.759769,0.750878,0.758281,0.761677,0.764816,0.765877

'Religion'

,BERT.F1-M.Org,BERT.F1-M.CF-0.1,BERT.F1-M.CF-0.2,BERT.F1-M.CF-0.3,BERT.F1-M.CF-0.4,BERT.F1-M.CF-0.5,BERT.F1-M.CF-0.6,BERT.F1-M.CF-0.7,BERT.F1-M.CF-0.8,BERT.F1-M.CF-0.9,BERT.F1-M.CF-1.0
0,0.667049,0.685933,0.688057,0.694392,0.683524,0.707903,0.702251,0.643452,0.675286,0.683878,0.672955
1,0.732907,0.747852,0.763479,0.767974,0.763727,0.746606,0.768277,0.781485,0.764860,0.742869,0.777425
2,0.736275,0.764140,0.746077,0.743437,0.719759,0.752045,0.739578,0.766458,0.764152,0.760251,0.745177
3,0.751442,0.834610,0.823849,0.852981,0.856673,0.800809,0.764697,0.779649,0.828461,0.788285,0.786527
4,0.577933,0.622045,0.528813,0.590602,0.671410,0.681361,0.629022,0.517501,0.621814,0.612336,0.679355
Mean,0.693121,0.730916,0.710055,0.729877,0.739019,0.737745,0.720765,0.697709,0.730915,0.717524,0.732288

'Race'

,BERT.F1-M.Org,BERT.F1-M.CF-0.1,BERT.F1-M.CF-0.2,BERT.F1-M.CF-0.3,BERT.F1-M.CF-0.4,BERT.F1-M.CF-0.5,BERT.F1-M.CF-0.6,BERT.F1-M.CF-0.7,BERT.F1-M.CF-0.8,BERT.F1-M.CF-0.9,BERT.F1-M.CF-1.0
0,0.636983,0.632866,0.686212,0.670302,0.641110,0.662790,0.675322,0.657247,0.672202,0.654459,0.644222
1,0.695540,0.719268,0.757928,0.668855,0.706955,0.692680,0.674522,0.655273,0.675361,0.642773,0.636970
2,0.773018,0.785143,0.787767,0.760930,0.748438,0.758120,0.785198,0.799169,0.786250,0.772131,0.769971
3,0.778101,0.756994,0.802137,0.757714,0.750962,0.752761,0.779859,0.793433,0.793455,0.770996,0.761913
4,0.587710,0.619222,0.631813,0.582839,0.608970,0.581564,0.581569,0.610075,0.597769,0.625253,0.540563
Mean,0.694270,0.702699,0.733171,0.688128,0.691287,0.689583,0.699294,0.703039,0.705007,0.693123,0.670728

'Politics'

,BERT.F1-M.Org,BERT.F1-M.CF-0.1,BERT.F1-M.CF-0.2,BERT.F1-M.CF-0.3,BERT.F1-M.CF-0.4,BERT.F1-M.CF-0.5,BERT.F1-M.CF-0.6,BERT.F1-M.CF-0.7,BERT.F1-M.CF-0.8,BERT.F1-M.CF-0.9,BERT.F1-M.CF-1.0
0,0.639140,0.634146,0.665416,0.664332,0.650320,0.643076,0.674007,0.629945,0.641207,0.661170,0.662139
1,0.746622,0.760810,0.763443,0.766253,0.783346,0.735692,0.796713,0.766392,0.773312,0.742748,0.769399
2,0.731199,0.692468,0.739872,0.752062,0.749481,0.709027,0.706748,0.768989,0.740172,0.767247,0.757588
3,0.808073,0.839452,0.744254,0.820874,0.856360,0.831580,0.827197,0.826997,0.859052,0.807086,0.858680
4,0.713681,0.738722,0.681603,0.722252,0.748942,0.752393,0.712995,0.758847,0.732196,0.745367,0.765456
Mean,0.727743,0.733120,0.718917,0.745154,0.757690,0.734354,0.743532,0.750234,0.749188,0.744724,0.762653

'Sports'

,BERT.F1-M.Org,BERT.F1-M.CF-0.1,BERT.F1-M.CF-0.2,BERT.F1-M.CF-0.3,BERT.F1-M.CF-0.4,BERT.F1-M.CF-0.5,BERT.F1-M.CF-0.6,BERT.F1-M.CF-0.7,BERT.F1-M.CF-0.8,BERT.F1-M.CF-0.9,BERT.F1-M.CF-1.0
0,0.638803,0.659505,0.646589,0.680561,0.588111,0.603784,0.602551,0.691122,0.632445,0.671549,0.657596
1,0.796641,0.803079,0.782862,0.735218,0.823687,0.670786,0.693973,0.735896,0.800510,0.734836,0.794106
2,0.761828,0.788380,0.804466,0.793137,0.780504,0.696011,0.770893,0.787206,0.806709,0.794664,0.749428
3,0.900791,0.897776,0.813875,0.883906,0.836986,0.890845,0.881468,0.907441,0.908581,0.900015,0.866163
4,0.714407,0.740027,0.692973,0.698123,0.780184,0.707501,0.727907,0.746047,0.707450,0.705902,0.687346
Mean,0.762494,0.777753,0.748153,0.758189,0.761894,0.713785,0.735358,0.773542,0.771139,0.761393,0.750928

In [20]:
res_w_lst = []
for domain, _df, _res_dict in  prepare_dataframe(bert_dict, 'BERT', m_lst = ['F1-Weighted']):
    res_w_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,BERT.F1-W.Org,BERT.F1-W.CF-0.1,BERT.F1-W.CF-0.2,BERT.F1-W.CF-0.3,BERT.F1-W.CF-0.4,BERT.F1-W.CF-0.5,BERT.F1-W.CF-0.6,BERT.F1-W.CF-0.7,BERT.F1-W.CF-0.8,BERT.F1-W.CF-0.9,BERT.F1-W.CF-1.0
0,0.913538,0.913920,0.909748,0.899609,0.902244,0.894189,0.872843,0.895743,0.909421,0.895995,0.895414
1,0.936324,0.915921,0.934453,0.933772,0.931942,0.937166,0.937447,0.901908,0.917166,0.927725,0.925381
2,0.952979,0.941465,0.961889,0.956267,0.963338,0.963521,0.962980,0.949619,0.956668,0.963695,0.963295
3,0.938504,0.953734,0.945872,0.964113,0.952985,0.953823,0.949073,0.947183,0.956992,0.949838,0.948095
4,0.834043,0.807755,0.855584,0.796009,0.862163,0.835054,0.831381,0.835125,0.832990,0.813646,0.843055
Mean,0.915078,0.906559,0.921509,0.909954,0.922535,0.916751,0.910745,0.905916,0.914647,0.910180,0.915048

'Religion'

,BERT.F1-W.Org,BERT.F1-W.CF-0.1,BERT.F1-W.CF-0.2,BERT.F1-W.CF-0.3,BERT.F1-W.CF-0.4,BERT.F1-W.CF-0.5,BERT.F1-W.CF-0.6,BERT.F1-W.CF-0.7,BERT.F1-W.CF-0.8,BERT.F1-W.CF-0.9,BERT.F1-W.CF-1.0
0,0.894726,0.892021,0.895741,0.895712,0.897775,0.903091,0.905610,0.884107,0.889553,0.888721,0.886639
1,0.936045,0.940706,0.934828,0.939185,0.943219,0.936320,0.924532,0.942683,0.934212,0.926336,0.942748
2,0.946829,0.945205,0.944150,0.944074,0.934635,0.950694,0.949273,0.939649,0.947602,0.948193,0.948703
3,0.956580,0.952066,0.960298,0.961228,0.963993,0.959461,0.946748,0.959006,0.957681,0.955482,0.962738
4,0.804437,0.811184,0.796808,0.798846,0.851449,0.837948,0.820584,0.814347,0.838273,0.831077,0.831350
Mean,0.907723,0.908237,0.906365,0.907809,0.918214,0.917503,0.909349,0.907959,0.913464,0.909962,0.914436

'Race'

,BERT.F1-W.Org,BERT.F1-W.CF-0.1,BERT.F1-W.CF-0.2,BERT.F1-W.CF-0.3,BERT.F1-W.CF-0.4,BERT.F1-W.CF-0.5,BERT.F1-W.CF-0.6,BERT.F1-W.CF-0.7,BERT.F1-W.CF-0.8,BERT.F1-W.CF-0.9,BERT.F1-W.CF-1.0
0,0.930503,0.923742,0.932063,0.927247,0.927923,0.930346,0.927819,0.928371,0.928353,0.926377,0.927152
1,0.948279,0.945827,0.952752,0.944881,0.947171,0.946684,0.942316,0.941426,0.945770,0.933121,0.939857
2,0.952411,0.957229,0.957434,0.947038,0.948848,0.949216,0.958590,0.955635,0.952726,0.952063,0.952717
3,0.947155,0.951853,0.953074,0.953981,0.953002,0.949930,0.953487,0.957903,0.955700,0.952106,0.945334
4,0.751931,0.737469,0.788570,0.740408,0.798786,0.758141,0.798196,0.796058,0.762751,0.767484,0.714166
Mean,0.906056,0.903224,0.916779,0.902711,0.915146,0.906863,0.916082,0.915879,0.909060,0.906230,0.895845

'Politics'

,BERT.F1-W.Org,BERT.F1-W.CF-0.1,BERT.F1-W.CF-0.2,BERT.F1-W.CF-0.3,BERT.F1-W.CF-0.4,BERT.F1-W.CF-0.5,BERT.F1-W.CF-0.6,BERT.F1-W.CF-0.7,BERT.F1-W.CF-0.8,BERT.F1-W.CF-0.9,BERT.F1-W.CF-1.0
0,0.870826,0.859646,0.866063,0.862821,0.848839,0.856478,0.868295,0.848191,0.840263,0.862198,0.861113
1,0.926239,0.930110,0.929367,0.928140,0.932815,0.928298,0.936567,0.934975,0.930529,0.926318,0.938326
2,0.928286,0.932133,0.939270,0.930273,0.937143,0.933401,0.935802,0.944626,0.935217,0.947430,0.937712
3,0.947672,0.950216,0.944684,0.947564,0.953542,0.951336,0.946821,0.950899,0.953439,0.945709,0.954228
4,0.842782,0.857256,0.849693,0.870329,0.863272,0.873102,0.871032,0.877216,0.877665,0.881546,0.873860
Mean,0.903161,0.905872,0.905815,0.907826,0.907122,0.908523,0.911703,0.911181,0.907423,0.912640,0.913048

'Sports'

,BERT.F1-W.Org,BERT.F1-W.CF-0.1,BERT.F1-W.CF-0.2,BERT.F1-W.CF-0.3,BERT.F1-W.CF-0.4,BERT.F1-W.CF-0.5,BERT.F1-W.CF-0.6,BERT.F1-W.CF-0.7,BERT.F1-W.CF-0.8,BERT.F1-W.CF-0.9,BERT.F1-W.CF-1.0
0,0.913520,0.909894,0.916855,0.917995,0.898142,0.912104,0.907916,0.913871,0.895140,0.906107,0.903259
1,0.964488,0.959254,0.959793,0.962093,0.962646,0.948575,0.958257,0.960993,0.959673,0.961290,0.964602
2,0.966642,0.966177,0.968525,0.966864,0.964776,0.961632,0.961840,0.972597,0.967550,0.974762,0.967131
3,0.980594,0.981512,0.974577,0.977434,0.974448,0.981079,0.980457,0.980738,0.980905,0.979976,0.977107
4,0.896726,0.908554,0.877092,0.883431,0.920492,0.876699,0.907938,0.914321,0.906479,0.900300,0.904761
Mean,0.944394,0.945078,0.939369,0.941563,0.944101,0.936018,0.943282,0.948504,0.941949,0.944487,0.943372

In [21]:
_df_bert = reduce(lambda x, y: pd.merge(pd.DataFrame(x), pd.DataFrame(y), on='Domain'), [res_m_lst, res_m_pj_lst, res_w_lst, res_w_pj_lst])
_df_bert.columns = _df_bert.columns.str.replace("BERT.", "")
print('BERT')
_df_bert

BERT

,Domain,$F1_M$,$F1_M.cf$,$F1_M.pj.cf$,$F1_W$,$F1_W.cf$,$F1_W.pj.cf$
0,Gender,0.770,0.781$_{cf=0.4}$,0.767$_{cf=0.7}$,0.915,0.923$_{cf=0.4}$,0.915$_{cf=0.1}$
1,Religion,0.693,0.739$_{cf=0.4}$,0.739$_{cf=0.4}$,0.908,0.918$_{cf=0.4}$,0.917$_{cf=1.0}$
2,Race,0.694,0.733$_{cf=0.2}$,0.725$_{cf=0.8}$,0.906,0.917$_{cf=0.2}$,0.916$_{cf=0.6}$
3,Politics,0.728,0.763$_{cf=1.0}$,0.769$_{cf=0.2}$,0.903,0.913$_{cf=1.0}$,0.911$_{cf=0.2}$
4,Sports,0.762,0.778$_{cf=0.1}$,0.777$_{cf=0.5}$,0.944,0.949$_{cf=0.7}$,0.949$_{cf=0.1}$

In [22]:
# _df_bert = pd.merge(pd.DataFrame(res_m_lst), pd.DataFrame(res_w_lst), on='Domain')
# _df_bert.columns = _df_bert.columns.str.replace("BERT.", "")
# print('BERT')
# _df_bert

In [23]:
for _df, c in [(_df_tpot, 'Shows result of TPOT pipeline'), (_df_davd, 'Shows result of Davidson pipeline'), (_df_bert, 'Shows results of BERT')]:
    print(_df.to_latex(index=False, caption=c))
    print()
    display(_df)

\begin{table}
\caption{Shows result of TPOT pipeline}
\begin{tabular}{lllllll}
\toprule
Domain & $F1_M$ & $F1_M.cf$ & $F1_M.pj.cf$ & $F1_W$ & $F1_W.cf$ & $F1_W.pj.cf$ \\
\midrule
Gender & 0.614 & 0.620$_{cf=0.3}$ & 0.613$_{cf=0.1}$ & 0.887 & 0.890$_{cf=0.4}$ & 0.888$_{cf=0.1}$ \\
Religion & 0.624 & 0.607$_{cf=0.1}$ & 0.613$_{cf=0.5}$ & 0.878 & 0.880$_{cf=0.6}$ & 0.873$_{cf=0.6}$ \\
Race & 0.581 & 0.585$_{cf=0.6}$ & 0.590$_{cf=0.3}$ & 0.876 & 0.881$_{cf=0.5}$ & 0.887$_{cf=1.0}$ \\
Politics & 0.627 & 0.639$_{cf=0.2}$ & 0.631$_{cf=0.3}$ & 0.878 & 0.885$_{cf=0.9}$ & 0.880$_{cf=0.2}$ \\
Sports & 0.683 & 0.674$_{cf=0.3}$ & 0.674$_{cf=0.2}$ & 0.932 & 0.935$_{cf=0.5}$ & 0.931$_{cf=0.2}$ \\
\bottomrule
\end{tabular}
\end{table}

,Domain,$F1_M$,$F1_M.cf$,$F1_M.pj.cf$,$F1_W$,$F1_W.cf$,$F1_W.pj.cf$
0,Gender,0.614,0.620$_{cf=0.3}$,0.613$_{cf=0.1}$,0.887,0.890$_{cf=0.4}$,0.888$_{cf=0.1}$
1,Religion,0.624,0.607$_{cf=0.1}$,0.613$_{cf=0.5}$,0.878,0.880$_{cf=0.6}$,0.873$_{cf=0.6}$
2,Race,0.581,0.585$_{cf=0.6}$,0.590$_{cf=0.3}$,0.876,0.881$_{cf=0.5}$,0.887$_{cf=1.0}$
3,Politics,0.627,0.639$_{cf=0.2}$,0.631$_{cf=0.3}$,0.878,0.885$_{cf=0.9}$,0.880$_{cf=0.2}$
4,Sports,0.683,0.674$_{cf=0.3}$,0.674$_{cf=0.2}$,0.932,0.935$_{cf=0.5}$,0.931$_{cf=0.2}$

\begin{table}
\caption{Shows result of Davidson pipeline}
\begin{tabular}{lllllll}
\toprule
Domain & $F1_M$ & $F1_M.cf$ & $F1_M.pj.cf$ & $F1_W$ & $F1_W.cf$ & $F1_W.pj.cf$ \\
\midrule
Gender & 0.649 & 0.655$_{cf=0.9}$ & 0.650$_{cf=0.6}$ & 0.882 & 0.885$_{cf=0.9}$ & 0.881$_{cf=0.1}$ \\
Religion & 0.595 & 0.606$_{cf=0.7}$ & 0.600$_{cf=0.9}$ & 0.838 & 0.852$_{cf=1.0}$ & 0.845$_{cf=0.4}$ \\
Race & 0.633 & 0.639$_{cf=1.0}$ & 0.645$_{cf=0.9}$ & 0.865 & 0.870$_{cf=1.0}$ & 0.871$_{cf=0.9}$ \\
Politics & 0.643 & 0.656$_{cf=0.9}$ & 0.654$_{cf=0.9}$ & 0.860 & 0.873$_{cf=1.0}$ & 0.868$_{cf=0.9}$ \\
Sports & 0.710 & 0.716$_{cf=0.9}$ & 0.716$_{cf=0.9}$ & 0.929 & 0.934$_{cf=0.9}$ & 0.929$_{cf=0.2}$ \\
\bottomrule
\end{tabular}
\end{table}

,Domain,$F1_M$,$F1_M.cf$,$F1_M.pj.cf$,$F1_W$,$F1_W.cf$,$F1_W.pj.cf$
0,Gender,0.649,0.655$_{cf=0.9}$,0.650$_{cf=0.6}$,0.882,0.885$_{cf=0.9}$,0.881$_{cf=0.1}$
1,Religion,0.595,0.606$_{cf=0.7}$,0.600$_{cf=0.9}$,0.838,0.852$_{cf=1.0}$,0.845$_{cf=0.4}$
2,Race,0.633,0.639$_{cf=1.0}$,0.645$_{cf=0.9}$,0.865,0.870$_{cf=1.0}$,0.871$_{cf=0.9}$
3,Politics,0.643,0.656$_{cf=0.9}$,0.654$_{cf=0.9}$,0.860,0.873$_{cf=1.0}$,0.868$_{cf=0.9}$
4,Sports,0.710,0.716$_{cf=0.9}$,0.716$_{cf=0.9}$,0.929,0.934$_{cf=0.9}$,0.929$_{cf=0.2}$

\begin{table}
\caption{Shows results of BERT}
\begin{tabular}{lllllll}
\toprule
Domain & $F1_M$ & $F1_M.cf$ & $F1_M.pj.cf$ & $F1_W$ & $F1_W.cf$ & $F1_W.pj.cf$ \\
\midrule
Gender & 0.770 & 0.781$_{cf=0.4}$ & 0.767$_{cf=0.7}$ & 0.915 & 0.923$_{cf=0.4}$ & 0.915$_{cf=0.1}$ \\
Religion & 0.693 & 0.739$_{cf=0.4}$ & 0.739$_{cf=0.4}$ & 0.908 & 0.918$_{cf=0.4}$ & 0.917$_{cf=1.0}$ \\
Race & 0.694 & 0.733$_{cf=0.2}$ & 0.725$_{cf=0.8}$ & 0.906 & 0.917$_{cf=0.2}$ & 0.916$_{cf=0.6}$ \\
Politics & 0.728 & 0.763$_{cf=1.0}$ & 0.769$_{cf=0.2}$ & 0.903 & 0.913$_{cf=1.0}$ & 0.911$_{cf=0.2}$ \\
Sports & 0.762 & 0.778$_{cf=0.1}$ & 0.777$_{cf=0.5}$ & 0.944 & 0.949$_{cf=0.7}$ & 0.949$_{cf=0.1}$ \\
\bottomrule
\end{tabular}
\end{table}

,Domain,$F1_M$,$F1_M.cf$,$F1_M.pj.cf$,$F1_W$,$F1_W.cf$,$F1_W.pj.cf$
0,Gender,0.770,0.781$_{cf=0.4}$,0.767$_{cf=0.7}$,0.915,0.923$_{cf=0.4}$,0.915$_{cf=0.1}$
1,Religion,0.693,0.739$_{cf=0.4}$,0.739$_{cf=0.4}$,0.908,0.918$_{cf=0.4}$,0.917$_{cf=1.0}$
2,Race,0.694,0.733$_{cf=0.2}$,0.725$_{cf=0.8}$,0.906,0.917$_{cf=0.2}$,0.916$_{cf=0.6}$
3,Politics,0.728,0.763$_{cf=1.0}$,0.769$_{cf=0.2}$,0.903,0.913$_{cf=1.0}$,0.911$_{cf=0.2}$
4,Sports,0.762,0.778$_{cf=0.1}$,0.777$_{cf=0.5}$,0.944,0.949$_{cf=0.7}$,0.949$_{cf=0.1}$

In [24]:
def prepare_ood_dataframe(res_dict, msg, m_lst = ['F1-Weighted'], sota=''):
    for d, exp_dict in res_dict.items():
        out_dict = {}
        # print(d, len(exp_dict['Org']), 'Org')
        if 'Org' in exp_dict:
            for splt_item in exp_dict['Org']:
                for m in m_lst:
                    v = splt_item[2]['Org'][0][m]
                    # print(v, splt_item)
                    k = msg + '.' + m[:4] + '.' + 'Org'
                    if not k in out_dict:
                        out_dict[k] = []    
                    out_dict[k].append(v)
        for CF, splt_items in exp_dict['CF'].items():
            for splt_item in splt_items:
                # print(CF, splt_item)
                for m in m_lst:
                    v = splt_item[2]['CF'][0][m]
                    k = msg + '.' + m[:4] + '.' + sota + 'CF-' + CF[:3]
                    if not k in out_dict:
                        out_dict[k] = []
                    out_dict[k].append(v)
        _res_df = pd.DataFrame(out_dict)
        
        _dict = _res_df.loc[0].to_dict()
        out_dict = {}
        out_dict['Domain'] = d
        if 'Org' in exp_dict:
            k = msg + '.' + m[:4] + '.' + 'Org'
            nk = '$' + msg + '.' + m[:2] + '_' + m[3] + '$'
            out_dict[nk] = f'{round(_dict[k], 3):.3f}'
            del _dict[k]
        for i, (_k, v) in enumerate(sorted(_dict.items(), key=lambda x:x[1], reverse=True)[:1]):
            k = msg + '.' + m[:4] + '.' + 'CF'
            nk = '$' + msg + '.' + m[:2] + '_' + m[3] + '.' + sota + 'cf' + '$'
            # if i == 1:
            #     nk += ' 2nd'
            # nk += ' Best'
            out_dict[nk] = f'{round(v, 3):.3f}' + '$_{cf=' + _k[-3:]+'}$'
        yield d, _res_df, out_dict

In [25]:
bert_ood_pj_res_file = 'out/bert-base-uncased-EP_5-ft-lshd22-heval19-ood-pj.json'
bert_ood_pj_dict = json.load(open(bert_ood_pj_res_file, "r"))

res_m_pj_lst = []
for domain, _df, _res_dict in  prepare_ood_dataframe(bert_ood_pj_dict, 'BERT-ood', m_lst = ['F1-Macro'], sota='pj.'):
    res_m_pj_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,BERT-ood.F1-M.pj.CF-0.1,BERT-ood.F1-M.pj.CF-0.2,BERT-ood.F1-M.pj.CF-0.3,BERT-ood.F1-M.pj.CF-0.4,BERT-ood.F1-M.pj.CF-0.5,BERT-ood.F1-M.pj.CF-0.6,BERT-ood.F1-M.pj.CF-0.7,BERT-ood.F1-M.pj.CF-0.8,BERT-ood.F1-M.pj.CF-0.9,BERT-ood.F1-M.pj.CF-1.0
0,0.52318,0.523895,0.515136,0.534245,0.529918,0.528695,0.526917,0.529745,0.527476,0.531543

'Religion'

,BERT-ood.F1-M.pj.CF-0.1,BERT-ood.F1-M.pj.CF-0.2,BERT-ood.F1-M.pj.CF-0.3,BERT-ood.F1-M.pj.CF-0.4,BERT-ood.F1-M.pj.CF-0.5,BERT-ood.F1-M.pj.CF-0.6,BERT-ood.F1-M.pj.CF-0.7,BERT-ood.F1-M.pj.CF-0.8,BERT-ood.F1-M.pj.CF-0.9,BERT-ood.F1-M.pj.CF-1.0
0,0.521011,0.523857,0.531494,0.535007,0.540461,0.532826,0.532659,0.525428,0.540549,0.543095

'Race'

,BERT-ood.F1-M.pj.CF-0.1,BERT-ood.F1-M.pj.CF-0.2,BERT-ood.F1-M.pj.CF-0.3,BERT-ood.F1-M.pj.CF-0.4,BERT-ood.F1-M.pj.CF-0.5,BERT-ood.F1-M.pj.CF-0.6,BERT-ood.F1-M.pj.CF-0.7,BERT-ood.F1-M.pj.CF-0.8,BERT-ood.F1-M.pj.CF-0.9,BERT-ood.F1-M.pj.CF-1.0
0,0.546474,0.550187,0.53613,0.538607,0.537905,0.539361,0.540056,0.537099,0.537248,0.543036

'Politics'

,BERT-ood.F1-M.pj.CF-0.1,BERT-ood.F1-M.pj.CF-0.2,BERT-ood.F1-M.pj.CF-0.3,BERT-ood.F1-M.pj.CF-0.4,BERT-ood.F1-M.pj.CF-0.5,BERT-ood.F1-M.pj.CF-0.6,BERT-ood.F1-M.pj.CF-0.7,BERT-ood.F1-M.pj.CF-0.8,BERT-ood.F1-M.pj.CF-0.9,BERT-ood.F1-M.pj.CF-1.0
0,0.523856,0.518081,0.536584,0.527184,0.531432,0.545593,0.530936,0.526379,0.527988,0.535103

'Sports'

,BERT-ood.F1-M.pj.CF-0.1,BERT-ood.F1-M.pj.CF-0.2,BERT-ood.F1-M.pj.CF-0.3,BERT-ood.F1-M.pj.CF-0.4,BERT-ood.F1-M.pj.CF-0.5,BERT-ood.F1-M.pj.CF-0.6,BERT-ood.F1-M.pj.CF-0.7,BERT-ood.F1-M.pj.CF-0.8,BERT-ood.F1-M.pj.CF-0.9,BERT-ood.F1-M.pj.CF-1.0
0,0.522667,0.517526,0.517039,0.526229,0.532379,0.526124,0.517946,0.531587,0.521285,0.51884

In [26]:
res_w_pj_lst = []
for domain, _df, _res_dict in  prepare_ood_dataframe(bert_ood_pj_dict, 'BERT-ood', m_lst = ['F1-Weighted'], sota='pj.'):
    res_w_pj_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,BERT-ood.F1-W.pj.CF-0.1,BERT-ood.F1-W.pj.CF-0.2,BERT-ood.F1-W.pj.CF-0.3,BERT-ood.F1-W.pj.CF-0.4,BERT-ood.F1-W.pj.CF-0.5,BERT-ood.F1-W.pj.CF-0.6,BERT-ood.F1-W.pj.CF-0.7,BERT-ood.F1-W.pj.CF-0.8,BERT-ood.F1-W.pj.CF-0.9,BERT-ood.F1-W.pj.CF-1.0
0,0.5303,0.530675,0.521756,0.542765,0.537991,0.537417,0.535016,0.538423,0.535894,0.540113

'Religion'

,BERT-ood.F1-W.pj.CF-0.1,BERT-ood.F1-W.pj.CF-0.2,BERT-ood.F1-W.pj.CF-0.3,BERT-ood.F1-W.pj.CF-0.4,BERT-ood.F1-W.pj.CF-0.5,BERT-ood.F1-W.pj.CF-0.6,BERT-ood.F1-W.pj.CF-0.7,BERT-ood.F1-W.pj.CF-0.8,BERT-ood.F1-W.pj.CF-0.9,BERT-ood.F1-W.pj.CF-1.0
0,0.523847,0.52759,0.534667,0.537809,0.545926,0.539603,0.534678,0.528744,0.547508,0.548212

'Race'

,BERT-ood.F1-W.pj.CF-0.1,BERT-ood.F1-W.pj.CF-0.2,BERT-ood.F1-W.pj.CF-0.3,BERT-ood.F1-W.pj.CF-0.4,BERT-ood.F1-W.pj.CF-0.5,BERT-ood.F1-W.pj.CF-0.6,BERT-ood.F1-W.pj.CF-0.7,BERT-ood.F1-W.pj.CF-0.8,BERT-ood.F1-W.pj.CF-0.9,BERT-ood.F1-W.pj.CF-1.0
0,0.550683,0.552538,0.538654,0.539444,0.542883,0.545281,0.5456,0.544975,0.544751,0.550908

'Politics'

,BERT-ood.F1-W.pj.CF-0.1,BERT-ood.F1-W.pj.CF-0.2,BERT-ood.F1-W.pj.CF-0.3,BERT-ood.F1-W.pj.CF-0.4,BERT-ood.F1-W.pj.CF-0.5,BERT-ood.F1-W.pj.CF-0.6,BERT-ood.F1-W.pj.CF-0.7,BERT-ood.F1-W.pj.CF-0.8,BERT-ood.F1-W.pj.CF-0.9,BERT-ood.F1-W.pj.CF-1.0
0,0.526268,0.514714,0.540168,0.53142,0.53528,0.556596,0.535914,0.528248,0.533677,0.539417

'Sports'

,BERT-ood.F1-W.pj.CF-0.1,BERT-ood.F1-W.pj.CF-0.2,BERT-ood.F1-W.pj.CF-0.3,BERT-ood.F1-W.pj.CF-0.4,BERT-ood.F1-W.pj.CF-0.5,BERT-ood.F1-W.pj.CF-0.6,BERT-ood.F1-W.pj.CF-0.7,BERT-ood.F1-W.pj.CF-0.8,BERT-ood.F1-W.pj.CF-0.9,BERT-ood.F1-W.pj.CF-1.0
0,0.522667,0.519945,0.518946,0.529287,0.538963,0.527717,0.520928,0.532562,0.528613,0.523998

In [27]:
bert_ood_res_file = 'out/bert-base-uncased-EP_5-ft-lshd22-heval19-ood.json'
bert_ood_dict = json.load(open(bert_ood_res_file, "r"))

res_m_lst = []
for domain, _df, _res_dict in  prepare_ood_dataframe(bert_ood_dict, 'BERT-ood', m_lst = ['F1-Macro']):
    res_m_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,BERT-ood.F1-M.Org,BERT-ood.F1-M.CF-0.1,BERT-ood.F1-M.CF-0.2,BERT-ood.F1-M.CF-0.3,BERT-ood.F1-M.CF-0.4,BERT-ood.F1-M.CF-0.5,BERT-ood.F1-M.CF-0.6,BERT-ood.F1-M.CF-0.7,BERT-ood.F1-M.CF-0.8,BERT-ood.F1-M.CF-0.9,BERT-ood.F1-M.CF-1.0
0,0.516074,0.517905,0.524955,0.524965,0.518526,0.51767,0.519727,0.514428,0.525422,0.523308,0.517211

'Religion'

,BERT-ood.F1-M.Org,BERT-ood.F1-M.CF-0.1,BERT-ood.F1-M.CF-0.2,BERT-ood.F1-M.CF-0.3,BERT-ood.F1-M.CF-0.4,BERT-ood.F1-M.CF-0.5,BERT-ood.F1-M.CF-0.6,BERT-ood.F1-M.CF-0.7,BERT-ood.F1-M.CF-0.8,BERT-ood.F1-M.CF-0.9,BERT-ood.F1-M.CF-1.0
0,0.522612,0.520064,0.521528,0.527445,0.529728,0.522157,0.535294,0.521055,0.521057,0.523082,0.540402

'Race'

,BERT-ood.F1-M.Org,BERT-ood.F1-M.CF-0.1,BERT-ood.F1-M.CF-0.2,BERT-ood.F1-M.CF-0.3,BERT-ood.F1-M.CF-0.4,BERT-ood.F1-M.CF-0.5,BERT-ood.F1-M.CF-0.6,BERT-ood.F1-M.CF-0.7,BERT-ood.F1-M.CF-0.8,BERT-ood.F1-M.CF-0.9,BERT-ood.F1-M.CF-1.0
0,0.510797,0.515504,0.512324,0.519279,0.524112,0.517999,0.526295,0.519899,0.527662,0.520359,0.525662

'Politics'

,BERT-ood.F1-M.Org,BERT-ood.F1-M.CF-0.1,BERT-ood.F1-M.CF-0.2,BERT-ood.F1-M.CF-0.3,BERT-ood.F1-M.CF-0.4,BERT-ood.F1-M.CF-0.5,BERT-ood.F1-M.CF-0.6,BERT-ood.F1-M.CF-0.7,BERT-ood.F1-M.CF-0.8,BERT-ood.F1-M.CF-0.9,BERT-ood.F1-M.CF-1.0
0,0.51475,0.518656,0.527002,0.522002,0.518317,0.516961,0.519326,0.512354,0.518216,0.515073,0.515583

'Sports'

,BERT-ood.F1-M.Org,BERT-ood.F1-M.CF-0.1,BERT-ood.F1-M.CF-0.2,BERT-ood.F1-M.CF-0.3,BERT-ood.F1-M.CF-0.4,BERT-ood.F1-M.CF-0.5,BERT-ood.F1-M.CF-0.6,BERT-ood.F1-M.CF-0.7,BERT-ood.F1-M.CF-0.8,BERT-ood.F1-M.CF-0.9,BERT-ood.F1-M.CF-1.0
0,0.517866,0.521997,0.520305,0.518,0.520094,0.514073,0.521,0.519594,0.512855,0.515704,0.523931

In [28]:
res_w_lst = []
for domain, _df, _res_dict in  prepare_ood_dataframe(bert_ood_dict, 'BERT-ood', m_lst = ['F1-Weighted']):
    res_w_lst.append(_res_dict)
    display(domain, _df)

'Gender'

,BERT-ood.F1-W.Org,BERT-ood.F1-W.CF-0.1,BERT-ood.F1-W.CF-0.2,BERT-ood.F1-W.CF-0.3,BERT-ood.F1-W.CF-0.4,BERT-ood.F1-W.CF-0.5,BERT-ood.F1-W.CF-0.6,BERT-ood.F1-W.CF-0.7,BERT-ood.F1-W.CF-0.8,BERT-ood.F1-W.CF-0.9,BERT-ood.F1-W.CF-1.0
0,0.521365,0.521581,0.532252,0.529044,0.522788,0.522635,0.525388,0.520773,0.529801,0.529384,0.523082

'Religion'

,BERT-ood.F1-W.Org,BERT-ood.F1-W.CF-0.1,BERT-ood.F1-W.CF-0.2,BERT-ood.F1-W.CF-0.3,BERT-ood.F1-W.CF-0.4,BERT-ood.F1-W.CF-0.5,BERT-ood.F1-W.CF-0.6,BERT-ood.F1-W.CF-0.7,BERT-ood.F1-W.CF-0.8,BERT-ood.F1-W.CF-0.9,BERT-ood.F1-W.CF-1.0
0,0.526202,0.521882,0.52283,0.529083,0.533089,0.524654,0.5374,0.525014,0.522897,0.525753,0.538637

'Race'

,BERT-ood.F1-W.Org,BERT-ood.F1-W.CF-0.1,BERT-ood.F1-W.CF-0.2,BERT-ood.F1-W.CF-0.3,BERT-ood.F1-W.CF-0.4,BERT-ood.F1-W.CF-0.5,BERT-ood.F1-W.CF-0.6,BERT-ood.F1-W.CF-0.7,BERT-ood.F1-W.CF-0.8,BERT-ood.F1-W.CF-0.9,BERT-ood.F1-W.CF-1.0
0,0.505162,0.517985,0.512662,0.518458,0.52797,0.517896,0.530842,0.522971,0.527436,0.522303,0.52589

'Politics'

,BERT-ood.F1-W.Org,BERT-ood.F1-W.CF-0.1,BERT-ood.F1-W.CF-0.2,BERT-ood.F1-W.CF-0.3,BERT-ood.F1-W.CF-0.4,BERT-ood.F1-W.CF-0.5,BERT-ood.F1-W.CF-0.6,BERT-ood.F1-W.CF-0.7,BERT-ood.F1-W.CF-0.8,BERT-ood.F1-W.CF-0.9,BERT-ood.F1-W.CF-1.0
0,0.517442,0.519016,0.531921,0.524016,0.52122,0.517656,0.519633,0.51433,0.521325,0.517788,0.517857

'Sports'

,BERT-ood.F1-W.Org,BERT-ood.F1-W.CF-0.1,BERT-ood.F1-W.CF-0.2,BERT-ood.F1-W.CF-0.3,BERT-ood.F1-W.CF-0.4,BERT-ood.F1-W.CF-0.5,BERT-ood.F1-W.CF-0.6,BERT-ood.F1-W.CF-0.7,BERT-ood.F1-W.CF-0.8,BERT-ood.F1-W.CF-0.9,BERT-ood.F1-W.CF-1.0
0,0.519152,0.521793,0.520894,0.517948,0.521809,0.517469,0.520974,0.520542,0.515297,0.520198,0.524845

In [29]:
_df_bert_ood = reduce(lambda x, y: pd.merge(pd.DataFrame(x), pd.DataFrame(y), on='Domain'), [res_m_lst, res_m_pj_lst, res_w_lst, res_w_pj_lst])
_df_bert_ood.columns = _df_bert_ood.columns.str.replace("BERT-ood.", "")
print('BERT_ood')
_df_bert_ood

BERT_ood

,Domain,$F1_M$,$F1_M.cf$,$F1_M.pj.cf$,$F1_W$,$F1_W.cf$,$F1_W.pj.cf$
0,Gender,0.516,0.525$_{cf=0.8}$,0.534$_{cf=0.4}$,0.521,0.532$_{cf=0.2}$,0.543$_{cf=0.4}$
1,Religion,0.523,0.540$_{cf=1.0}$,0.543$_{cf=1.0}$,0.526,0.539$_{cf=1.0}$,0.548$_{cf=1.0}$
2,Race,0.511,0.528$_{cf=0.8}$,0.550$_{cf=0.2}$,0.505,0.531$_{cf=0.6}$,0.553$_{cf=0.2}$
3,Politics,0.515,0.527$_{cf=0.2}$,0.546$_{cf=0.6}$,0.517,0.532$_{cf=0.2}$,0.557$_{cf=0.6}$
4,Sports,0.518,0.524$_{cf=1.0}$,0.532$_{cf=0.5}$,0.519,0.525$_{cf=1.0}$,0.539$_{cf=0.5}$

In [30]:
# _df_bert_ood = pd.merge(pd.DataFrame(res_m_lst), pd.DataFrame(res_w_lst), on='Domain')
# _df_bert_ood.columns = _df_bert_ood.columns.str.replace("BERT-ood.", "")
# print('BERT_ood')
# _df_bert_ood

In [31]:
for _df, c in [(_df_bert_ood, 'Shows result of BERT with out-of-domain experiment')]:
    print(_df.to_latex(index=False, caption=c))
    print()
    display(_df)

\begin{table}
\caption{Shows result of BERT with out-of-domain experiment}
\begin{tabular}{lllllll}
\toprule
Domain & $F1_M$ & $F1_M.cf$ & $F1_M.pj.cf$ & $F1_W$ & $F1_W.cf$ & $F1_W.pj.cf$ \\
\midrule
Gender & 0.516 & 0.525$_{cf=0.8}$ & 0.534$_{cf=0.4}$ & 0.521 & 0.532$_{cf=0.2}$ & 0.543$_{cf=0.4}$ \\
Religion & 0.523 & 0.540$_{cf=1.0}$ & 0.543$_{cf=1.0}$ & 0.526 & 0.539$_{cf=1.0}$ & 0.548$_{cf=1.0}$ \\
Race & 0.511 & 0.528$_{cf=0.8}$ & 0.550$_{cf=0.2}$ & 0.505 & 0.531$_{cf=0.6}$ & 0.553$_{cf=0.2}$ \\
Politics & 0.515 & 0.527$_{cf=0.2}$ & 0.546$_{cf=0.6}$ & 0.517 & 0.532$_{cf=0.2}$ & 0.557$_{cf=0.6}$ \\
Sports & 0.518 & 0.524$_{cf=1.0}$ & 0.532$_{cf=0.5}$ & 0.519 & 0.525$_{cf=1.0}$ & 0.539$_{cf=0.5}$ \\
\bottomrule
\end{tabular}
\end{table}

,Domain,$F1_M$,$F1_M.cf$,$F1_M.pj.cf$,$F1_W$,$F1_W.cf$,$F1_W.pj.cf$
0,Gender,0.516,0.525$_{cf=0.8}$,0.534$_{cf=0.4}$,0.521,0.532$_{cf=0.2}$,0.543$_{cf=0.4}$
1,Religion,0.523,0.540$_{cf=1.0}$,0.543$_{cf=1.0}$,0.526,0.539$_{cf=1.0}$,0.548$_{cf=1.0}$
2,Race,0.511,0.528$_{cf=0.8}$,0.550$_{cf=0.2}$,0.505,0.531$_{cf=0.6}$,0.553$_{cf=0.2}$
3,Politics,0.515,0.527$_{cf=0.2}$,0.546$_{cf=0.6}$,0.517,0.532$_{cf=0.2}$,0.557$_{cf=0.6}$
4,Sports,0.518,0.524$_{cf=1.0}$,0.532$_{cf=0.5}$,0.519,0.525$_{cf=1.0}$,0.539$_{cf=0.5}$

In [32]:
from config import HEVAL_DATAFILE
import pandas as pd
# Labels:0 (nonhate) 1 (hate)
df_test = pd.read_csv(HEVAL_DATAFILE)
df_test = df_test.rename(columns={'text': 'Tweet', 'HS': 'Label', 'id': 'TweetID'})
df_test.Label.value_counts()

Label
0    1740
1    1260
Name: count, dtype: int64

In [33]:
1260/3000

0.42

In [34]:
bert_ood_full_res_file = 'out/bert-base-uncased-EP_5-ft-lshd22-heval19-ood-full.json'
bert_ood_full_dict = json.load(open(bert_ood_full_res_file, "r"))

res_m_lst = []
for domain, _df, _res_dict in  prepare_ood_dataframe(bert_ood_full_dict, 'BERT-ood-full', m_lst = ['F1-Macro']):
    res_m_lst.append(_res_dict)
    display(domain, _df)

'Complete'

,BERT-ood-full.F1-M.Org,BERT-ood-full.F1-M.CF-0.1,BERT-ood-full.F1-M.CF-0.2,BERT-ood-full.F1-M.CF-0.3,BERT-ood-full.F1-M.CF-0.4,BERT-ood-full.F1-M.CF-0.5,BERT-ood-full.F1-M.CF-0.6,BERT-ood-full.F1-M.CF-0.7,BERT-ood-full.F1-M.CF-0.8,BERT-ood-full.F1-M.CF-0.9,BERT-ood-full.F1-M.CF-1.0
0,0.521725,0.517315,0.520134,0.524305,0.526407,0.514487,0.523099,0.521869,0.523452,0.51834,0.535475

In [35]:
bert_ood_full_res_file = 'out/bert-base-uncased-EP_5-ft-lshd22-heval19-ood-full.json'
bert_ood_full_dict = json.load(open(bert_ood_full_res_file, "r"))

res_m_lst = []
for domain, _df, _res_dict in  prepare_ood_dataframe(bert_ood_full_dict, 'BERT-ood-full', m_lst = ['F1-Macro']):
    res_m_lst.append(_res_dict)
    display(domain, _df)

'Complete'

,BERT-ood-full.F1-M.Org,BERT-ood-full.F1-M.CF-0.1,BERT-ood-full.F1-M.CF-0.2,BERT-ood-full.F1-M.CF-0.3,BERT-ood-full.F1-M.CF-0.4,BERT-ood-full.F1-M.CF-0.5,BERT-ood-full.F1-M.CF-0.6,BERT-ood-full.F1-M.CF-0.7,BERT-ood-full.F1-M.CF-0.8,BERT-ood-full.F1-M.CF-0.9,BERT-ood-full.F1-M.CF-1.0
0,0.521725,0.517315,0.520134,0.524305,0.526407,0.514487,0.523099,0.521869,0.523452,0.51834,0.535475

In [36]:
res_w_lst = []
for domain, _df, _res_dict in  prepare_ood_dataframe(bert_ood_full_dict, 'BERT-ood-full', m_lst = ['F1-Weighted']):
    res_w_lst.append(_res_dict)
    display(domain, _df)

'Complete'

,BERT-ood-full.F1-W.Org,BERT-ood-full.F1-W.CF-0.1,BERT-ood-full.F1-W.CF-0.2,BERT-ood-full.F1-W.CF-0.3,BERT-ood-full.F1-W.CF-0.4,BERT-ood-full.F1-W.CF-0.5,BERT-ood-full.F1-W.CF-0.6,BERT-ood-full.F1-W.CF-0.7,BERT-ood-full.F1-W.CF-0.8,BERT-ood-full.F1-W.CF-0.9,BERT-ood-full.F1-W.CF-1.0
0,0.524454,0.5194,0.523973,0.524889,0.530802,0.519277,0.527474,0.526102,0.526731,0.523298,0.536986

In [37]:
_df_bert_full_ood = pd.merge(pd.DataFrame(res_m_lst), pd.DataFrame(res_w_lst), on='Domain')
_df_bert_full_ood.columns = _df_bert_full_ood.columns.str.replace("BERT-ood-full.", "")
print('BERT_full_ood')
_df_bert_full_ood

BERT_full_ood

     Domain $F1_M$         $F1_M.cf$ $F1_W$         $F1_W.cf$
0  Complete  0.522  0.535$_{cf=1.0}$  0.524  0.537$_{cf=1.0}$

# Experiment 3

In [38]:
def prepare_ood_man_cf_dataframe(res_dict, msg, m_lst = ['F1-Weighted'], sota=''):
    out_dict = {}
    if 'Org' in res_dict:
        for splt_item in res_dict['Org']:
            for m in m_lst:
                v = splt_item[2]['Org'][0][m]
                # print(v, splt_item)
                k = msg + '.' + m[:4] + '.' + 'Org'
                if not k in out_dict:
                    out_dict[k] = []    
                out_dict[k].append(v)
    for CF, splt_items in res_dict['CF'].items():
        for splt_item in splt_items:
            # print(CF, splt_item)
            for m in m_lst:
                v = splt_item[2]['CF'][0][m]
                k = msg + '.' + m[:4] + '.' + sota + 'CF-' + CF[:3]
                if not k in out_dict:
                    out_dict[k] = []
                out_dict[k].append(v)
    # print(res_dict['ManCF'].items())
    if 'ManCF' in res_dict:
        for CF, splt_items in res_dict['ManCF'].items():
            for splt_item in splt_items:
                # print(CF, splt_item)
                for m in m_lst:
                    v = splt_item[2]['CF'][0][m]
                    k = msg + '.' + m[:4] + '.' + 'ManCF-' + CF[:3]
                    if not k in out_dict:
                        out_dict[k] = []
                    out_dict[k].append(v)
    _res_df = pd.DataFrame(out_dict)
    
    _dict = _res_df.loc[0].to_dict()
    def filter_keys(d, _str):
        for k in list(d.keys()):
            if k.find(_str)>-1:
                del d[k]
        return d
    _cf_dict = _res_df.loc[0].to_dict()
    if 'ManCF' in res_dict and 'Org' in res_dict:
        _cf_dict = filter_keys(filter_keys(_cf_dict, '.ManCF'), '.Org')

    if 'ManCF' in res_dict:
        _mancf_dict = _res_df.loc[0].to_dict()
        _mancf_dict = filter_keys(filter_keys(_mancf_dict, '.'+ sota + 'CF'), '.Org')
    if 'Org' in res_dict:
        k = msg + '.' + m[:4] + '.' + 'Org'
        nk = '$' + msg + '.' + m[:2] + '_' + m[3] + '$'
        out_dict = {}
        # out_dict['Domain'] = d
        # print(nk)
        out_dict[nk] = f'{round(_dict[k], 3):.3f}'
        del _dict[k]
    # print(_dict.keys())
    roundoff = lambda v: f'{round(v, 3):.3f}'
    # k = msg + '.' + m[:4] + '.' + 'CF'
    if sota:
        out_dict = {}

    nk = '$' + msg + '.' + m[:2] + '_' + m[3] + '.' + sota + 'cf' + '$'
    # if 'ManCF' in res_dict and 'Org' in res_dict:
    for i, (_k, v) in enumerate(sorted(_cf_dict.items(), key=lambda x:x[1], reverse=True)[:1]):
        
        # if i == 1:
        #     nk += ' 2nd'
        # nk += ' Best'
        # print(nk)
        out_dict[nk] = f'{round(v, 3):.3f}' + '$_{cf=' + _k[-3:]+'}$'
    # print(_cf_dict.keys())
    out_dict['$\\bar{x}({' + nk[1:-1] + '})$'] = roundoff(statistics.mean(_cf_dict.values()))
    out_dict['$\\sigma({' + nk[1:-1] + '})$'] = roundoff(statistics.stdev(_cf_dict.values()))
    
    # k = msg + '.' + m[:4] + '.' + 'ManCF'
    nk = '$' + msg + '.' + m[:2] + '_' + m[3] + '.' + 'mancf' + '$'
    if 'ManCF' in res_dict:
        for i, (_k, v) in enumerate(sorted(_mancf_dict.items(), key=lambda x:x[1], reverse=True)[:1]):
            
            # if i == 1:
            #     nk += ' 2nd'
            # nk += ' Best'
            # print(nk)
            out_dict[nk] = f'{round(v, 3):.3f}' + '$_{cf=' + _k[-3:]+'}$'
        
        out_dict['$\\bar{x}({' + nk[1:-1] + '})$'] = roundoff(statistics.mean(_mancf_dict.values()))
        out_dict['$\\sigma({' + nk[1:-1] + '})$'] = roundoff(statistics.stdev(_mancf_dict.values()))
        # out_dict[nk] = statistics.stdev(_mancf_dict.values()))
        # print(_mancf_dict.keys())
    print(out_dict)
    yield _res_df, out_dict


# bert_ood_man_cf_res_file = 'out/bert-base-uncased-EP_5-ft-vidh21-heval19-ood.json'
# bert_ood_man_cf_dict = json.load(open(bert_ood_man_cf_res_file, "r"))

# res_m_lst = []
# for _df, _res_dict in  prepare_ood_man_cf_dataframe(bert_ood_man_cf_dict, 'BERT-ood', m_lst = ['F1-Macro']):
#     res_m_lst.append(_res_dict)
#     display(_df)
# res_m_pj_lst = []
# for _df, _res_dict in  prepare_ood_man_cf_dataframe(bert_ood_man_cf_pj_dict, 'BERT-ood', m_lst = ['F1-Macro'], sota='pj.'):
#     res_m_pj_lst.append(_res_dict)
#     display(_df)

In [39]:
bert_ood_man_cf_gpt_pj_mixed_res_file = 'out/bert-base-uncased-EP_5-ft-vidh21-heval19-ood-gpt-pj-mixed.json'
bert_ood_man_cf_gtp_pj__mixed_dict = json.load(open(bert_ood_man_cf_gpt_pj_mixed_res_file, "r"))

res_m_gpt_pj_mixed_lst = []
for _df, _res_dict in  prepare_ood_man_cf_dataframe(bert_ood_man_cf_gtp_pj__mixed_dict, 'BERT-ood', m_lst = ['F1-Macro'], sota='comb.'):
    res_m_gpt_pj_mixed_lst.append(_res_dict)
    display(_df)

{'$BERT-ood.F1_M.comb.cf$': '0.658$_{cf=0.6}$', '$\\bar{x}({BERT-ood.F1_M.comb.cf})$': '0.638', '$\\sigma({BERT-ood.F1_M.comb.cf})$': '0.015'}

,BERT-ood.F1-M.comb.CF-0.1,BERT-ood.F1-M.comb.CF-0.2,BERT-ood.F1-M.comb.CF-0.3,BERT-ood.F1-M.comb.CF-0.4,BERT-ood.F1-M.comb.CF-0.5,BERT-ood.F1-M.comb.CF-0.6,BERT-ood.F1-M.comb.CF-0.7,BERT-ood.F1-M.comb.CF-0.8,BERT-ood.F1-M.comb.CF-0.9,BERT-ood.F1-M.comb.CF-1.0
0,0.654778,0.633274,0.62336,0.633822,0.641137,0.657785,0.61625,0.620641,0.648788,0.651422

In [40]:
res_w_gpt_pj_mixed_lst = []
for _df, _res_dict in  prepare_ood_man_cf_dataframe(bert_ood_man_cf_gtp_pj__mixed_dict, 'BERT-ood', m_lst = ['F1-Weighted'], sota='comb.'):
    res_w_gpt_pj_mixed_lst.append(_res_dict)
    display(_df)

{'$BERT-ood.F1_W.comb.cf$': '0.666$_{cf=0.1}$', '$\\bar{x}({BERT-ood.F1_W.comb.cf})$': '0.647', '$\\sigma({BERT-ood.F1_W.comb.cf})$': '0.014'}

,BERT-ood.F1-W.comb.CF-0.1,BERT-ood.F1-W.comb.CF-0.2,BERT-ood.F1-W.comb.CF-0.3,BERT-ood.F1-W.comb.CF-0.4,BERT-ood.F1-W.comb.CF-0.5,BERT-ood.F1-W.comb.CF-0.6,BERT-ood.F1-W.comb.CF-0.7,BERT-ood.F1-W.comb.CF-0.8,BERT-ood.F1-W.comb.CF-0.9,BERT-ood.F1-W.comb.CF-1.0
0,0.66612,0.632531,0.640454,0.641224,0.648046,0.664757,0.625522,0.637717,0.657723,0.658263

In [41]:
bert_ood_man_cf_pj_res_file = 'out/bert-base-uncased-EP_5-ft-vidh21-heval19-ood-pj.json'
bert_ood_man_cf_pj_dict = json.load(open(bert_ood_man_cf_pj_res_file, "r"))

res_m_pj_lst = []
for _df, _res_dict in  prepare_ood_man_cf_dataframe(bert_ood_man_cf_pj_dict, 'BERT-ood', m_lst = ['F1-Macro'], sota='pj.'):
    res_m_pj_lst.append(_res_dict)
    display(_df)

{'$BERT-ood.F1_M.pj.cf$': '0.638$_{cf=0.3}$', '$\\bar{x}({BERT-ood.F1_M.pj.cf})$': '0.620', '$\\sigma({BERT-ood.F1_M.pj.cf})$': '0.016'}

,BERT-ood.F1-M.pj.CF-0.1,BERT-ood.F1-M.pj.CF-0.2,BERT-ood.F1-M.pj.CF-0.3,BERT-ood.F1-M.pj.CF-0.4,BERT-ood.F1-M.pj.CF-0.5,BERT-ood.F1-M.pj.CF-0.6,BERT-ood.F1-M.pj.CF-0.7,BERT-ood.F1-M.pj.CF-0.8,BERT-ood.F1-M.pj.CF-0.9,BERT-ood.F1-M.pj.CF-1.0
0,0.624383,0.5926,0.638433,0.597393,0.628208,0.630239,0.614491,0.60641,0.629434,0.635621

In [42]:
res_w_pj_lst = []
for _df, _res_dict in  prepare_ood_man_cf_dataframe(bert_ood_man_cf_pj_dict, 'BERT-ood', m_lst = ['F1-Weighted'], sota='pj.'):
    res_w_pj_lst.append(_res_dict)
    display(_df)

{'$BERT-ood.F1_W.pj.cf$': '0.648$_{cf=0.3}$', '$\\bar{x}({BERT-ood.F1_W.pj.cf})$': '0.631', '$\\sigma({BERT-ood.F1_W.pj.cf})$': '0.016'}

,BERT-ood.F1-W.pj.CF-0.1,BERT-ood.F1-W.pj.CF-0.2,BERT-ood.F1-W.pj.CF-0.3,BERT-ood.F1-W.pj.CF-0.4,BERT-ood.F1-W.pj.CF-0.5,BERT-ood.F1-W.pj.CF-0.6,BERT-ood.F1-W.pj.CF-0.7,BERT-ood.F1-W.pj.CF-0.8,BERT-ood.F1-W.pj.CF-0.9,BERT-ood.F1-W.pj.CF-1.0
0,0.637023,0.605811,0.647843,0.600506,0.637527,0.641085,0.631557,0.621608,0.638091,0.647067

In [43]:
bert_ood_man_cf_res_file = 'out/bert-base-uncased-EP_5-ft-vidh21-heval19-ood.json'
bert_ood_man_cf_dict = json.load(open(bert_ood_man_cf_res_file, "r"))

res_m_lst = []
for _df, _res_dict in  prepare_ood_man_cf_dataframe(bert_ood_man_cf_dict, 'BERT-ood', m_lst = ['F1-Macro']):
    res_m_lst.append(_res_dict)
    display(_df)

{'$BERT-ood.F1_M$': '0.584', '$BERT-ood.F1_M.cf$': '0.653$_{cf=0.9}$', '$\\bar{x}({BERT-ood.F1_M.cf})$': '0.617', '$\\sigma({BERT-ood.F1_M.cf})$': '0.025', '$BERT-ood.F1_M.mancf$': '0.631$_{cf=0.6}$', '$\\bar{x}({BERT-ood.F1_M.mancf})$': '0.607', '$\\sigma({BERT-ood.F1_M.mancf})$': '0.027'}

,BERT-ood.F1-M.Org,BERT-ood.F1-M.CF-0.1,BERT-ood.F1-M.CF-0.2,BERT-ood.F1-M.CF-0.3,BERT-ood.F1-M.CF-0.4,BERT-ood.F1-M.CF-0.5,BERT-ood.F1-M.CF-0.6,BERT-ood.F1-M.CF-0.7,BERT-ood.F1-M.CF-0.8,BERT-ood.F1-M.CF-0.9,...,BERT-ood.F1-M.ManCF-0.1,BERT-ood.F1-M.ManCF-0.2,BERT-ood.F1-M.ManCF-0.3,BERT-ood.F1-M.ManCF-0.4,BERT-ood.F1-M.ManCF-0.5,BERT-ood.F1-M.ManCF-0.6,BERT-ood.F1-M.ManCF-0.7,BERT-ood.F1-M.ManCF-0.8,BERT-ood.F1-M.ManCF-0.9,BERT-ood.F1-M.ManCF-1.0
0,0.58415,0.59967,0.604094,0.575874,0.623834,0.62201,0.641959,0.638944,0.624065,0.65335,...,0.61289,0.617675,0.625402,0.588259,0.544613,0.631102,0.584982,0.630001,0.62359,0.613387

In [44]:
res_w_lst = []
for _df, _res_dict in  prepare_ood_man_cf_dataframe(bert_ood_man_cf_dict, 'BERT-ood', m_lst = ['F1-Weighted']):
    res_w_lst.append(_res_dict)
    display(_df)

{'$BERT-ood.F1_W$': '0.606', '$BERT-ood.F1_W.cf$': '0.664$_{cf=0.9}$', '$\\bar{x}({BERT-ood.F1_W.cf})$': '0.630', '$\\sigma({BERT-ood.F1_W.cf})$': '0.021', '$BERT-ood.F1_W.mancf$': '0.644$_{cf=0.6}$', '$\\bar{x}({BERT-ood.F1_W.mancf})$': '0.624', '$\\sigma({BERT-ood.F1_W.mancf})$': '0.022'}

,BERT-ood.F1-W.Org,BERT-ood.F1-W.CF-0.1,BERT-ood.F1-W.CF-0.2,BERT-ood.F1-W.CF-0.3,BERT-ood.F1-W.CF-0.4,BERT-ood.F1-W.CF-0.5,BERT-ood.F1-W.CF-0.6,BERT-ood.F1-W.CF-0.7,BERT-ood.F1-W.CF-0.8,BERT-ood.F1-W.CF-0.9,...,BERT-ood.F1-W.ManCF-0.1,BERT-ood.F1-W.ManCF-0.2,BERT-ood.F1-W.ManCF-0.3,BERT-ood.F1-W.ManCF-0.4,BERT-ood.F1-W.ManCF-0.5,BERT-ood.F1-W.ManCF-0.6,BERT-ood.F1-W.ManCF-0.7,BERT-ood.F1-W.ManCF-0.8,BERT-ood.F1-W.ManCF-0.9,BERT-ood.F1-W.ManCF-1.0
0,0.605508,0.619142,0.610111,0.600191,0.637998,0.639327,0.64257,0.648899,0.626471,0.664221,...,0.630543,0.632784,0.639227,0.605563,0.574389,0.644343,0.607958,0.637539,0.635776,0.632336

In [45]:
res_m_gpt_pj_mixed_lst, res_m_gpt_pj_mixed_lst, res_m_pj_lst, res_w_pj_lst, res_m_lst, res_w_lst

([{'$BERT-ood.F1_M.comb.cf$': '0.658$_{cf=0.6}$',
   '$\\bar{x}({BERT-ood.F1_M.comb.cf})$': '0.638',
   '$\\sigma({BERT-ood.F1_M.comb.cf})$': '0.015'}],
 [{'$BERT-ood.F1_M.comb.cf$': '0.658$_{cf=0.6}$',
   '$\\bar{x}({BERT-ood.F1_M.comb.cf})$': '0.638',
   '$\\sigma({BERT-ood.F1_M.comb.cf})$': '0.015'}],
 [{'$BERT-ood.F1_M.pj.cf$': '0.638$_{cf=0.3}$',
   '$\\bar{x}({BERT-ood.F1_M.pj.cf})$': '0.620',
   '$\\sigma({BERT-ood.F1_M.pj.cf})$': '0.016'}],
 [{'$BERT-ood.F1_W.pj.cf$': '0.648$_{cf=0.3}$',
   '$\\bar{x}({BERT-ood.F1_W.pj.cf})$': '0.631',
   '$\\sigma({BERT-ood.F1_W.pj.cf})$': '0.016'}],
 [{'$BERT-ood.F1_M$': '0.584',
   '$BERT-ood.F1_M.cf$': '0.653$_{cf=0.9}$',
   '$\\bar{x}({BERT-ood.F1_M.cf})$': '0.617',
   '$\\sigma({BERT-ood.F1_M.cf})$': '0.025',
   '$BERT-ood.F1_M.mancf$': '0.631$_{cf=0.6}$',
   '$\\bar{x}({BERT-ood.F1_M.mancf})$': '0.607',
   '$\\sigma({BERT-ood.F1_M.mancf})$': '0.027'}],
 [{'$BERT-ood.F1_W$': '0.606',
   '$BERT-ood.F1_W.cf$': '0.664$_{cf=0.9}$',
   '$\\bar{x}({BERT-ood.F1_W.cf})$': '0.630',
   '$\\sigma({BERT-ood.F1_W.cf})$': '0.021',
   '$BERT-ood.F1_W.mancf$': '0.644$_{cf=0.6}$',
   '$\\bar{x}({BERT-ood.F1_W.mancf})$': '0.624',
   '$\\sigma({BERT-ood.F1_W.mancf})$': '0.022'}])

In [46]:
_df_bert_ood = pd.concat([pd.DataFrame(res_m_lst), pd.DataFrame(res_m_pj_lst), pd.DataFrame(res_m_gpt_pj_mixed_lst), pd.DataFrame(res_w_lst), pd.DataFrame(res_w_pj_lst), pd.DataFrame(res_w_gpt_pj_mixed_lst)],  axis=1)
_df_bert_ood.columns = _df_bert_ood.columns.str.replace("BERT-ood.", "")
print('BERT_ood')
_df_bert_ood

BERT_ood

,$F1_M$,$F1_M.cf$,$\bar{x}({F1_M.cf})$,$\sigma({F1_M.cf})$,$F1_M.mancf$,$\bar{x}({F1_M.mancf})$,$\sigma({F1_M.mancf})$,$F1_M.pj.cf$,$\bar{x}({F1_M.pj.cf})$,$\sigma({F1_M.pj.cf})$,...,$\sigma({F1_W.cf})$,$F1_W.mancf$,$\bar{x}({F1_W.mancf})$,$\sigma({F1_W.mancf})$,$F1_W.pj.cf$,$\bar{x}({F1_W.pj.cf})$,$\sigma({F1_W.pj.cf})$,$F1_W.comb.cf$,$\bar{x}({F1_W.comb.cf})$,$\sigma({F1_W.comb.cf})$
0,0.584,0.653$_{cf=0.9}$,0.617,0.025,0.631$_{cf=0.6}$,0.607,0.027,0.638$_{cf=0.3}$,0.620,0.016,...,0.021,0.644$_{cf=0.6}$,0.624,0.022,0.648$_{cf=0.3}$,0.631,0.016,0.666$_{cf=0.1}$,0.647,0.014

In [47]:
# # _df_bert_ood = pd.merge(pd.DataFrame(res_m_lst), pd.DataFrame(res_w_lst), on='Domain')
# _df_bert_ood = pd.concat([pd.DataFrame(res_m_lst), pd.DataFrame(res_w_lst)],  axis=1)
# _df_bert_ood.columns = _df_bert_ood.columns.str.replace("BERT-ood.", "")
# print('BERT_ood')
# _df_bert_ood

In [48]:
_df_bert_ood.columns

Index(['$F1_M$', '$F1_M.cf$', '$\bar{x}({F1_M.cf})$', '$\sigma({F1_M.cf})$',
       '$F1_M.mancf$', '$\bar{x}({F1_M.mancf})$', '$\sigma({F1_M.mancf})$',
       '$F1_M.pj.cf$', '$\bar{x}({F1_M.pj.cf})$', '$\sigma({F1_M.pj.cf})$',
       '$F1_M.comb.cf$', '$\bar{x}({F1_M.comb.cf})$',
       '$\sigma({F1_M.comb.cf})$', '$F1_W$', '$F1_W.cf$',
       '$\bar{x}({F1_W.cf})$', '$\sigma({F1_W.cf})$', '$F1_W.mancf$',
       '$\bar{x}({F1_W.mancf})$', '$\sigma({F1_W.mancf})$', '$F1_W.pj.cf$',
       '$\bar{x}({F1_W.pj.cf})$', '$\sigma({F1_W.pj.cf})$', '$F1_W.comb.cf$',
       '$\bar{x}({F1_W.comb.cf})$', '$\sigma({F1_W.comb.cf})$'],
      dtype='object')

In [49]:
col_primary = ['$F1_M$', '$F1_M.cf$', '$F1_M.pj.cf$', '$F1_M.comb.cf$', '$F1_M.mancf$', '$F1_W$', '$F1_W.cf$', '$F1_W.pj.cf$', '$F1_W.comb.cf$', '$F1_W.mancf$']
col_des_stats = ['$F1_M$', '$\\bar{x}({F1_M.cf})$', '$\\sigma({F1_M.cf})$',
                 '$\\bar{x}({F1_M.pj.cf})$', '$\\sigma({F1_M.pj.cf})$',
                 '$\\bar{x}({F1_M.comb.cf})$', '$\\sigma({F1_M.comb.cf})$',
                 '$\\bar{x}({F1_M.mancf})$', '$\\sigma({F1_M.mancf})$',
                 '$F1_W$',
                 '$\\bar{x}({F1_W.cf})$', '$\\sigma({F1_W.cf})$',
                 '$\\bar{x}({F1_W.pj.cf})$', '$\\sigma({F1_W.pj.cf})$',
                 '$\\bar{x}({F1_W.comb.cf})$', '$\\sigma({F1_W.comb.cf})$',
                 '$\\bar{x}({F1_W.mancf})$', '$\\sigma({F1_W.mancf})$']

In [50]:
for _df, c in [(_df_bert_ood[col_primary], 'Shows result of BERT with out-of-domain experiment comparing Manual CF with GPT-CF and without CF')]:
    print(_df.to_latex(index=False, caption=c))
    print()
_df_bert_ood[col_primary]

\begin{table}
\caption{Shows result of BERT with out-of-domain experiment comparing Manual CF with GPT-CF and without CF}
\begin{tabular}{llllllllll}
\toprule
$F1_M$ & $F1_M.cf$ & $F1_M.pj.cf$ & $F1_M.comb.cf$ & $F1_M.mancf$ & $F1_W$ & $F1_W.cf$ & $F1_W.pj.cf$ & $F1_W.comb.cf$ & $F1_W.mancf$ \\
\midrule
0.584 & 0.653$_{cf=0.9}$ & 0.638$_{cf=0.3}$ & 0.658$_{cf=0.6}$ & 0.631$_{cf=0.6}$ & 0.606 & 0.664$_{cf=0.9}$ & 0.648$_{cf=0.3}$ & 0.666$_{cf=0.1}$ & 0.644$_{cf=0.6}$ \\
\bottomrule
\end{tabular}
\end{table}

,$F1_M$,$F1_M.cf$,$F1_M.pj.cf$,$F1_M.comb.cf$,$F1_M.mancf$,$F1_W$,$F1_W.cf$,$F1_W.pj.cf$,$F1_W.comb.cf$,$F1_W.mancf$
0,0.584,0.653$_{cf=0.9}$,0.638$_{cf=0.3}$,0.658$_{cf=0.6}$,0.631$_{cf=0.6}$,0.606,0.664$_{cf=0.9}$,0.648$_{cf=0.3}$,0.666$_{cf=0.1}$,0.644$_{cf=0.6}$

In [51]:
for _df, c in [(_df_bert_ood[col_des_stats], 'Shows result of BERT with out-of-domain experiment comparing Manual CF with GPT-CF and without CF - Mean and STD')]:
    print(_df.to_latex(index=False, caption=c))
    print()
_df_bert_ood[col_des_stats]

\begin{table}
\caption{Shows result of BERT with out-of-domain experiment comparing Manual CF with GPT-CF and without CF - Mean and STD}
\begin{tabular}{llllllllllllllllll}
\toprule
$F1_M$ & $\bar{x}({F1_M.cf})$ & $\sigma({F1_M.cf})$ & $\bar{x}({F1_M.pj.cf})$ & $\sigma({F1_M.pj.cf})$ & $\bar{x}({F1_M.comb.cf})$ & $\sigma({F1_M.comb.cf})$ & $\bar{x}({F1_M.mancf})$ & $\sigma({F1_M.mancf})$ & $F1_W$ & $\bar{x}({F1_W.cf})$ & $\sigma({F1_W.cf})$ & $\bar{x}({F1_W.pj.cf})$ & $\sigma({F1_W.pj.cf})$ & $\bar{x}({F1_W.comb.cf})$ & $\sigma({F1_W.comb.cf})$ & $\bar{x}({F1_W.mancf})$ & $\sigma({F1_W.mancf})$ \\
\midrule
0.584 & 0.617 & 0.025 & 0.620 & 0.016 & 0.638 & 0.015 & 0.607 & 0.027 & 0.606 & 0.630 & 0.021 & 0.631 & 0.016 & 0.647 & 0.014 & 0.624 & 0.022 \\
\bottomrule
\end{tabular}
\end{table}

,$F1_M$,$\bar{x}({F1_M.cf})$,$\sigma({F1_M.cf})$,$\bar{x}({F1_M.pj.cf})$,$\sigma({F1_M.pj.cf})$,$\bar{x}({F1_M.comb.cf})$,$\sigma({F1_M.comb.cf})$,$\bar{x}({F1_M.mancf})$,$\sigma({F1_M.mancf})$,$F1_W$,$\bar{x}({F1_W.cf})$,$\sigma({F1_W.cf})$,$\bar{x}({F1_W.pj.cf})$,$\sigma({F1_W.pj.cf})$,$\bar{x}({F1_W.comb.cf})$,$\sigma({F1_W.comb.cf})$,$\bar{x}({F1_W.mancf})$,$\sigma({F1_W.mancf})$
0,0.584,0.617,0.025,0.620,0.016,0.638,0.015,0.607,0.027,0.606,0.630,0.021,0.631,0.016,0.647,0.014,0.624,0.022

In [52]:
print('done')

done